### ISSUE TITLE
Units for quantity missing (eg. kg/year)

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#100]
Page of interest: http://88.249.18.205:8090/ecoman/new_flow/65

Can you add some quantity units, such as kg/year, m3/year, pieces/year, kg/month, m3/month, and pieces/ month)?

**Comment by corner82** [comment]
Mr.Tuna has been coded related code blocks, so I assign him this issue, he later can mark milestone...

**Comment by tcgumus** [comment]
New units have been added.

**Comment by emilyvuylsteke** [comment]
Thank you for this!
