### ISSUE TITLE
"edit" button in the "company flows" box

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#101]
Page of interest:  http://88.249.18.205:8090/ecoman/new_flow/65

Please add “edit” button aside from the “delete” button on the far right of the “company flows” box.

**Comment by corner82** [comment]
Mr.Tuna has been coded related code blocks, so I assign him this issue, he later can mark milestone...

**Comment by catherine-moser** [comment]
This feature would be really important for users!

**Comment by tcgumus** [comment]
I know! we will make it!

**Comment by catherine-moser** [comment]
Ok, perfect.

I just added the issue

Possibility to change default value for cost unit? #210

But i couldn't add a label (should be datasetmanagement and enhancement.) how do I do that?

Thanks, Catherine


------------------------------------------------------------
Fachhochschule Nordwestschweiz FHNW
Hochschule für Life Sciences
Institut für Ecopreneurship

Dipl. Ing. FH Catherine Moser
Wissenschaftliche Mitarbeiterin
Gründenstrasse 40
CH-4132 Muttenz
------------------------------------------------------------
T +41 61 467 44 71
catherine.moser@fhnw.ch
www.fhnw.ch/hls/iec
-------------------------------------------------------------------------

Von: Tuna Çağlar Gümüş [mailto:notifications@github.com]
Gesendet: Freitag, 20. März 2015 12:03
An: Leadera/ecoman_repo
Cc: Moser Catherine
Betreff: Re: [ecoman_repo] "edit" button in the "company flows" box (#101)


I know! we will make it!

**Comment by tcgumus** [comment]
you can select labels by clicking labels field in the right side of the issue page :)
![image](https://cloud.githubusercontent.com/assets/2714346/6750395/68805b9a-cf02-11e4-9c94-da55439a64d4.png)

**Comment by catherine-moser** [comment]
For me it looks like this and nothing happens if  i click on lables, Catherine

[cid:image001.png@01D0630F.38B52800][cid:image002.jpg@01D0630F.38B52800]


Von: Tuna Çağlar Gümüş [mailto:notifications@github.com]
Gesendet: Freitag, 20. März 2015 12:10
An: Leadera/ecoman_repo
Cc: Moser Catherine
Betreff: Re: [ecoman_repo] "edit" button in the "company flows" box (#101)


you can select labels by clicking labels field in the right side of the issue page :)
[image]<https://cloud.githubusercontent.com/assets/2714346/6750395/68805b9a-cf02-11e4-9c94-da55439a64d4.png>

**Comment by catherine-moser** [comment]
If i start a new issue it looks like this and again i can't add lables…

[cid:image001.jpg@01D06312.2310F760]

Von: Tuna Çağlar Gümüş [mailto:notifications@github.com]
Gesendet: Freitag, 20. März 2015 12:10
An: Leadera/ecoman_repo
Cc: Moser Catherine
Betreff: Re: [ecoman_repo] "edit" button in the "company flows" box (#101)


you can select labels by clicking labels field in the right side of the issue page :)
[Das Bild wurde vom Absender entfernt. image]<https://cloud.githubusercontent.com/assets/2714346/6750395/68805b9a-cf02-11e4-9c94-da55439a64d4.png>

**Comment by tcgumus** [comment]
Edit feature has been added

**Comment by emilyvuylsteke** [comment]
Perfect. Thank you for the "edit" button.
