### ISSUE TITLE
Display only projects related to the current user account

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#102]
Page of interest: http://88.249.18.205:8090/ecoman/projects

When displaying the project page, we need to see only existing project related to the account of current user (for confidentiality reasons). There is no need to see all existing project on the platform (only super admin user should be able to see them).

**Comment by corner82** [comment]
Mr.Tuna has been coded related code blocks, so I assign him this issue, he later can mark milestone...

**Comment by tcgumus** [comment]
Users can now only see the projects they can edit in projects page
