### ISSUE TITLE
Map of involved companies per project

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#103]
Page of interest: http://88.249.18.205:8090/ecoman/project/17

Would it be possible to show on a map the involved companies in the project page? Can you please add a GIS functionality on this page to display all companies related to this specific project.

**Comment by corner82** [comment]
Would you please add me as consultant for project with id '17', 'Geneva test 1'. Because I'm not assigned to the project, I can not display the page, after assigning please let me know writing a comment for this issue, thank you

**Comment by corner82** [comment]
project companies related has been implemented, code repo has been updated
