### ISSUE TITLE
New company and related flow do not appear in IS scoping company list

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#104]
Page of interest: http://88.249.18.205:8090/ecoman/isscopingauto

The companies and related flows previously registered within one project do not appear in the list of the IS scoping. 
Plus, the IS scoping should be related to a project. Only the companies involved in the specific project should be included in the list of companies in the IS scoping. Indeed, some companies will enter confidential data and should not be accessible to all.

**Comment by corner82** [comment]
'The companies and related flows previously registered within one project do not appear in the list of the IS scoping.'

Companies registered earlier was added to the project in the early stages before 'MySql-PostgreSQL' conversion and IS related database triggers has been written, so if these companies cause confusion better to delete them. But in the sake of data consistency , these early companies cannot be added to 'IS' related processes.

**Comment by corner82** [comment]
İf IS scoping is per project bases, how can an user select all IS potentilas all around the Industrial zone, so I'm a little bit confused there , I will open a 'Question type' issue and I will try to explain my doubts and may be we should discuss how will this new feature will be implemented. maybe bu hangout meetimg we can discuss issue in a more detailed manner.

**Comment by gmassard** [comment]
Hi!
The all functionnalities has to be "project base". The idea is that when we develop a new case study in Switzerland, the IS scoping should only involve the companies for which we entered data. We do not need to see the Turkish companies when detecting IS in Switzerland.
Also they are confidentiality issues. We do not want data on Turkish companies to be available for new users in Switzerland or other countries in the futur...
Is it more clear now?

**Comment by corner82** [comment]
Hi Guillaume,
İf I remember right,
on ecoman, users can insert flows to directly companies,
but I 'm not sure are they restricted to their own companies , so all data
verifications and insertions is not per project bases for now I assume,
I think we should make meeting as soon as possibble with all contributors
to clear this issue (maybe we have necessary maesures about this topics and
I dont know details),
anyway a meeting will be helpful, maybe Tuna can give brief information on
this topics and I can figure out what to do

**Comment by corner82** [comment]
New trigger has been added to database, when user inserts a company, that company information is inserted into IS database tables.

**Comment by gmassard** [comment]
Issue not closed! I was not able to test it so far! Link between a project page and IS scoping page does not exist.
Let's wait until test if successful before closing an issue.

**Comment by corner82** [comment]
This issue label has been changed to 'waiting for testing', if it complies requirement needs, please close this issue

**Comment by gmassard** [comment]
We tested it with Zeynel,
I works for him! But not for my projects. Only Pouly appears.
Zeynel will look at it!

**Comment by corner82** [comment]
I looked why this bug may occur, at first look , I figured out that soma
companies which have been inserted into system before  launch our database
table for IS pages, so now companies that does not enlist in our IS tables
are as follows;
"Company Ostim A";39
"Reddit";8
"EMGE CO";9
"dikili a.s";34
"Company A";35
"Company B";36
"Company B";37
"Aktaş Holding";45
"Test Company";41
"Givaudan";65
"Givaudan";66
"LEM";67
"Serbeco";68
"Ostim Teknoloji A.Ş.";7
"Company Ostim B";40
"adasdasd";42
"COMPANY TEST 3";43
"Company C";61
"Company D";62
"Company E";63
"Erkap";44
"ADA Savunma Sanayi-Makine";25
"ANADOLU METALURJİ";51
"AREL";52
"ARGES";53
"BİYOTAR";54
"BMD SOLAR";55
"DAMLA KİMYA";56
"DASA KABLO";57
"ENERBAY";58
"EPTIM";59
"GES";60
"ALPIN";50
"Aktif İletişim";46
"ARGEN";47
"ART Elek.";48
"ASAŞ";49
"Sofies";64
"Consultant Company";69

When I insert a new company from scratch and add that company to project ,
I can see that company listed on IS pages too, I will implement absent
company data to IS tables by manually for once for the sake of tests , I
will inform when insert done.

**Comment by corner82** [comment]
I inserted absent company data on IS tables, checked new data seems there is no absent company now on IS tables, so changing issue label to 'waiting for testing', tester can close issue if test results are approved.

**Comment by gmassard** [comment]
Ok!
