### ISSUE TITLE
"select all company" button in the IS scoping

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#105]
Page of interest: http://88.249.18.205:8090/ecoman/isscopingauto

Can you add a “select all companies” button for selection of all companies in the “Company Flow Sets” box?

**Comment by corner82** [comment]
New 'select all companies' button has been added to page of interest. Alson git repo has been updated.

**Comment by emilyvuylsteke** [comment]
I'm sorry I do not see the "select all companies" button on the page http://88.249.18.205:8090/ecoman/isScopingAutoPrjBase#add

Am I missing it? If yes, please let me know. 

Thanks in advance!

**Comment by corner82** [comment]
Hi Emily , here is a screen shot from yoru link, 
![select_all_companies](https://cloud.githubusercontent.com/assets/5053878/6798225/adb34682-d213-11e4-9070-17ec72fc1ed6.png)
