### ISSUE TITLE
"select a flow category" error message

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#106]
Page of interest: http://88.249.18.205:8090/ecoman/isscopingauto

When I click on “calculate IS potential” in the “Company Flow Sets” box, it regularly asks to "select a flow category", even if they are all selected in the “flow category” box (default) (See printscreen). Then, if I manually select them, it works. 
![screen shot 2015-01-16 at 16 36 19](https://cloud.githubusercontent.com/assets/10558805/5779669/fdff7280-9da4-11e4-8c60-65c081b90bd8.png)

**Comment by corner82** [comment]
Tree root level ceheck boxes and their related nodes has been unchecked as page loaded, new warning messages has been added, several javascript and rest api page has been updated and committed to repo related with issue number
