### ISSUE TITLE
"select only one row" error message

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#107]
Page of interest: http://88.249.18.205:8090/ecoman/isscopingauto

When I select several IS potential in the “Dynamic table with IS potentials” box, and then click on “add Potential IS”, I get a message saying to select only one (see printscreen). It should be possible to select more than one.

![image](https://cloud.githubusercontent.com/assets/10558805/5779732/681c39e6-9da5-11e4-9b6b-ec7ba03856eb.png)

**Comment by corner82** [comment]
Multiple selection feature hass been added, code repo has been updated.
