### ISSUE TITLE
IS scoping per project basis

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#108]
I have some doubts about this functionality, so I will try to point out some issues,

1- If we handle  IS scoping project basis , how can we make IS assumptions about all companies and flows on industrial zone level,

2- Maybe we should consider one or more pages for IS scoping to make IS  analysis per project base and Industrial zone base according to users already defined / or will be defined,

3- So this issue can be related to 'users and roles' issue, so maybe Mr.Tuna can participate on this subject if a user for this purpose has been created in the system ('Super User' alike), if not what will be our initiative  about 'Users and Roles' issues and how will be implemented on ECOMAN generally,

4- So as you see I'm a little stucked here, we should make a live meeting as soon as posiible I think,

Thanks for yours quick responses about issues from all related parts and contributors, thank you...

**Comment by gmassard** [comment]
1- If we handle IS scoping project basis , how can we make IS assumptions about all companies and flows on industrial zone level,
Answer from Guillaume: One "project" is related to one industrial area. So all data entered in the database about the companies in the same industrial area should be available in the same project.

2- Maybe we should consider one or more pages for IS scoping to make IS analysis per project base and Industrial zone base according to users already defined / or will be defined
Answer from Guillaume: there are no need to several pages if you understand point number 1.

I ready to take part to an Hangout meeting if it can help solve the issue.

Best, Guillaume

**Comment by corner82** [comment]
Hi Guillaume,
maybe a meeting will make things clearer and faster on my side, thank you

**Comment by gmassard** [comment]
Ok! Can you please contact Tuna to discuss the issue and then organize a hangout meeting. I have availability this week or next week!
We actually have a meeting on Wednesday at 2pm CET time. We can use this group meeting to discuss the issue?

**Comment by corner82** [comment]
Sure I think this meeting on wednesday will best oppurtunity,
thank you ,
Regards,

**Comment by tcgumus** [comment]
Ok. Wednesday is also good for me. Regards.

**Comment by corner82** [comment]
This functionality has been added as seperate IS pages for Consultants use only, the old pages still remain for a possible consultant supervisor role in the future.

**Comment by gmassard** [comment]
The issue is not close in my opinion. When I click on the "project page", I can see my projects: http://88.249.18.205:8090/ecoman/projects
But then, how do I go to the IS scoping? I can't even test the IS scoping to see if it is now project based. Navigability is weak so far.
I'm reopening the issue

**Comment by corner82** [comment]
Now you can open a project and see IS pages links, so I'm closing this issue, but testing IS pages issue #104
