### ISSUE TITLE
Navigability in the IS scoping

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#109]
Page of interest: http://88.249.18.205:8090/ecoman/isscoping 

1. If you’re able to select specific flows, or all of them, It it not necessary to give the choice to either do the “IS process by all flow” or by selected flows. Related question: why does the “dynamic table with IS potentials” gives flows that are not in the selection of flow category? Is it because it is interesting to have a broader view at this stage? 
First answer by Zeynel: IS Process by all flows' scenario has been documented on 'IS scenarios' document, so was implemented, I see that there is no necessity this approach while you can select all flows, but in this approach companies flows is being/ or can be displayed more detail manner maybe, we can talk about that issue,

2. The results layout is not very clear and user friendly. Results layout (structure proposed by GMA)

- Row for each scenario (such as it is now)
- Clic on rowà companies involved in the scenario
- Clic on company’s à direct access to data modification. Reason: would be useful to go further in the assessment of the IS opportunity. Indeed, when there is a detection of possible symbiosis for one flow, more details on the form, price,etc. are needed to confirm the opportunity. There would be no need to enter all the parameters before this stage.
First answer by Zeynel: Result layouts datagrid has to be improved for details view, we can pick the necessity data and columns in a detailed manner, we can write those issues on a development document, and I assume many options can be implemented to become more friendly and get more useful data on interface to guide consultants

**Comment by corner82** [comment]
This feature details will be discussed after 'consultant open project' issue has been implemented on the software over all.

**Comment by gmassard** [comment]
I will close this issue and open new ones for IS scoping refinement.
