### ISSUE TITLE
Add new process family, new flow family in admin pages.

### ISSUE THREAD

**Issue by tcgumus** [Leadera/ecoman_repo#114]

**Comment by tcgumus** [comment]
Please check these links and test admin pages.
http://88.249.18.205:8090/ecoman/admin/newFlow
http://88.249.18.205:8090/ecoman/admin/newProcess
http://88.249.18.205:8090/ecoman/admin/newEquipment

**Comment by gmassard** [comment]
The fonctionalities works! Nicely done!
Next step is the integration of the admin page in the interface, with login functionalities and role definition.
Right?
