### ISSUE TITLE
Mapping of companies in project page

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#120]
Page of interest: http://88.249.18.205:8090/ecoman/project/17

About the “ see project companies on map” button
o	It does not seem to work. Could you center map on geographical location of companies and locate company’s with tag?
o	Could you please display map on the same page and not with a pop out ?
o	Could the button appear even if the user is not a consultant?

**Comment by corner82** [comment]
Hi, it worked for me , here is the screen shot, you can show what does not work form on screen share later 
![companies_onmap](https://cloud.githubusercontent.com/assets/5053878/5961285/348d477a-a7e4-11e4-9eb5-839744f028c2.png)

**Comment by corner82** [comment]
İf this issue seems good working, if further tests show new fixes , new issue can be opened.
