### ISSUE TITLE
Company flow page: add button to go back to company profile page

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#121]
Page of interest: http://88.249.18.205:8090/ecoman/new_flow/68

When you are on the company flow page, please add a button to go back to company profile.

Also, on the same page, please add a button (or a choice list) to go directly to a related project page.
So from page http://88.249.18.205:8090/ecoman/new_flow/68  the button should alow to go to page http://88.249.18.205:8090/ecoman/project/19

**Comment by tcgumus** [comment]
Now you can go directly to company page from dataset management page. You can click the company name
![image](https://cloud.githubusercontent.com/assets/2714346/6867608/81401744-d48c-11e4-8379-833daac83c21.png)
or you can click "go to company page" button
![image](https://cloud.githubusercontent.com/assets/2714346/6867613/91e33d88-d48c-11e4-8253-71bcbf9e5399.png)
you can also access the project page in every page by clicking project name on the header.
![image](https://cloud.githubusercontent.com/assets/2714346/6867635/ac075f3c-d48c-11e4-93d8-f33943b5f9b3.png)

**Comment by gmassard** [comment]
Ok, issue can be closed
