### ISSUE TITLE
GIS localisation of a project

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#125]
Page of interest: http://88.249.18.205:8090/ecoman/newproject

While creating a project, the user should be able to define a central geographical point for the project on a map. Then, as all pages are related to one specific project, all GIS maps displayed in other pages (other GIS functionalities on the platform) are automatically centered on that point when opened.

**Comment by corner82** [comment]
Dear all, modifications for this isuue has been completed as you see above, issues #135 and #136 has been launcehed for this issue's work, issue label has been changed to 'waiting for testing'  please test and if it complies needs you may close this issue.

**Comment by gmassard** [comment]
Next add:
1. User should be able to define the radius (zoom level) when creating a project.
2. When map open of project center selection. Center map on Europe with zoom out. (see the entire europe).
3. For further implementation of company location and advanced feature, we wait until "project management" issues are all solved.

**Comment by corner82** [comment]
1. User should be able to define the radius (zoom level) when creating a project. 
      This feature has been added, see #138
2. When map open of project center selection. Center map on Europe with zoom out. (see the entire europe).
      This feature has been added, see #138

changing label for this issue for 'waiting for test', if this requirement is fullfilled tester can close issue.

**Comment by gmassard** [comment]
I tested the functionality with Zeynel. It seems to wait.
