### ISSUE TITLE
Company page: alphabetic order and map for localisation 

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#126]
Page of interest: http://88.249.18.205:8090/ecoman/company

Could the companies be listed in alphabetic order?
Could there be a map localizing the companies of this list?

Remark: the company page should be adapted to the “project approach”. Thus, only companies related to the opened project should be displayed on the list and on the map.

**Comment by tcgumus** [comment]
alphabetic order completed.

**Comment by emilyvuylsteke** [comment]
Thank you for this!
