### ISSUE TITLE
"Units" for product quantity

### ISSUE THREAD

**Issue by MildaMa** [Leadera/ecoman_repo#142]
Page of interest: http://88.249.18.205:8090/ecoman/new_product/63
The field for "Unit" for product quantity is missing in the Dataset management->Product page.

**Comment by tcgumus** [comment]
Units for quantity added the product creation pages in dataset management.
![image](https://cloud.githubusercontent.com/assets/2714346/6867653/e6cc781e-d48c-11e4-86ba-e0bd2d40c546.png)

**Comment by catherine-moser** [comment]
Thanks.
