### ISSUE TITLE
Automated IS: data not align to headers

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#144]
When displaying the Is search result in the low left table, data is not align with headers.
Please check other tables as well.

**Comment by corner82** [comment]
on related page 'tt_grid_dynamic'  datagrid properties have been changed to 'fit:true', 'fitColumns : true',
changin this isuues label to 'waiting for testing' , if the requirement is ok, tester may close issue

**Comment by gmassard** [comment]
tested! Ok! Thanks!
