### ISSUE TITLE
The layout and navigation of CP scoping should have the same design as IS scoping

### ISSUE THREAD

**Issue by MildaMa** [Leadera/ecoman_repo#146]

**Comment by tcgumus** [comment]
Features of both scoping pages are different. You cant expect the same layout in every page. If is there a problem with the layout of cp scoping please right it directly

**Comment by MildaMa** [comment]
Hi Tuna,
sure. But it is not about the layout itself. It is about the design in CP scoping, which looks very different from IS scoping.
