### ISSUE TITLE
KPIs vs benchamrk KPIs graph: bugs  

### ISSUE THREAD

**Issue by MildaMa** [Leadera/ecoman_repo#148]
1. If Benachmark KPI is set to 0 it gives error in the graph. If Benchmark KPI=0, it should also indicate benchmark value for comparison. (see attached screenshot).
2. There are two processes in the table, but three columns in the graph (see attached screenshot). Why?

![error benchmark kpi 2015 02 18](https://cloud.githubusercontent.com/assets/9460158/6245302/7d171920-b75d-11e4-9950-57f757c96623.png)

**Comment by tcgumus** [comment]
Before moving into solve this error i would like to ask if there is a possibility of KPI value to be 0? 
Can you also add me as a consultant to this project so i can see it also? 
Thank you

**Comment by MildaMa** [comment]
Hi Tuna,
thanks for your answer.
No, KPI value cannot be 0.
As for the Benchmark KPI=0 we still have to discuss what exactly should be displayed. So let`s leave this question open for now.

**Comment by tcgumus** [comment]
Can we test it in new KPI pages. It looks like problem solved.

**Comment by catherine-moser** [comment]
yup, is solved.
