### ISSUE TITLE
Calculation of KPI: bug

### ISSUE THREAD

**Issue by MildaMa** [Leadera/ecoman_repo#149]
In Flow Allocation to Process page:
1. The calculated value of KPI (amount/reference) is rounded to integer. It means if amount value =10, reference value=30 it gives KPI=0 (should be KPI= 0.333..). This KPI=0 value later also gives 0 in KPI vs Benchmark KPI comparison table and graph. It means that if calculated KPI=0 (which is in fact 0.333...) and  the provided benchmark KPI=0.2 the graph shows that KPI does not exceed the Benchmark.
2. The calculated KPIs should not be rounded to integer. It should be displayed as xE+-0y (e.g. 3E-04)  or in case of bigger numbers rounded to 2 or 3 decimal places.

![rounding of kpi 2015 02 18](https://cloud.githubusercontent.com/assets/9460158/6245636/edcdba86-b760-11e4-96fb-423660ad4b10.png)

**Comment by tcgumus** [comment]
Hello,
KPI  problem is solved. Can you check and respond.
Thank you

**Comment by MildaMa** [comment]
Dear Tuna,
thanks for improvement. Would it also be possible to display it in xE+-0y (e.g. 3E-04) format for very small/big numbers?

**Comment by tcgumus** [comment]
It should be automatically displayed like you said when the numbers are too large or small.
1234567890123 will become 1.23456789012E+012. 
After the 12 digit. It will convert itself this format. But we can change the precision to another number. Should we change it?

**Comment by catherine-moser** [comment]
The display of big and small numbers is a general issue. We should agree on a default that we use throughout the platform. It should be easy to read and of course the program needs to be able to cope with it.

Big numbers: thousands separator is different in various countries e.g. 1 Mio is displayed like this:
Turkey: 1.000.000,00
US/GB: 1,000,000.00
Swiss: 1'000'000.00 or 1'000'000,00

I propose to use a space as a thousand separator (according to Wikipedia ISO 31 says to use space). For the decimal mark standards allow point or comma. I personally prefer point. (1 000 000.00)

For numbers bigger than 9 999 999 or smaler than 0.0001 I propose to use the scientific notation of 1.00E7 (10 Mio) respectively 9.99E-4 (0.00099).

What do you guys think?

**Comment by tcgumus** [comment]
Showing the values with E is ok but entering and calculating it will be hard. I think we can only use scientific notations for showing. 

Also user can be able to choose a display method and system will show all data based on it. It will be like language options in user setting pages.

**Comment by tcgumus** [comment]
I will not close this issue since KPI bug has been fixed. We can talk about notations in its issue.
https://github.com/Leadera/ecoman_repo/issues/320
