### ISSUE TITLE
CP scoping: enhancement for  "KPI view and edit table"

### ISSUE THREAD

**Issue by MildaMa** [Leadera/ecoman_repo#152]
For better navigability I would suggest to add a link to KPI calculation next to the KPI value in the "KPI view and edit table". This would allow editing the KPI directly from the table.

**Comment by tcgumus** [comment]
Hello,
I have changed the KPI calculation table and make it more readable and simple. I have also added the "edit allocation" button to it so you can directly go to allocation page of a KPI by clicking on it. 

![screen shot 2015-05-19 at 11 52 16](https://cloud.githubusercontent.com/assets/2714346/7700256/ae8d38de-fe1d-11e4-94b8-ccc88ed7ceb3.png)

**Comment by catherine-moser** [comment]
ok
