### ISSUE TITLE
Flow does not appaear in CP scoping

### ISSUE THREAD

**Issue by Ecoxl** [Leadera/ecoman_repo#153]
Dear Tuna
In data set data set management I created a process "company" and allocated the "flows" "steel". Then I crated again  a process "company" and allocated the "flows" "electrcity". Both processes and flows appaer on the compay page. But in In CP Scoping the Process and flow "company" electrcity" does not appear and allocation of amounts is not possible.
The comapany name is "HLS" if you want to look on it.
Chhers Dirk

**Comment by tcgumus** [comment]
I just take a look and it looks like you didn't make any allocation for these process and flows. You should create an allocation for these processes and flows to see them in cp scoping and kpi calculation pages. There is only 1 process (sawing) with 1 flow (steel) now.

**Comment by tcgumus** [comment]
We have tested this issue together. Allocation pages works well.
