### ISSUE TITLE
IS scoping improvement 1: company flow sets table improvement

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#154]
Main upper table:
It is a too long list to display all flow names that exist in the system as column.
I suggest to display the data like in the data management page. And display only the 4 column in the picture below. Only add one column on the left with company name. So the consultant can observe all data.
Ok for you?
![image1_isscoping](https://cloud.githubusercontent.com/assets/9587966/6411225/c499c6b0-be76-11e4-88ee-e9e54ddb6102.png)

**Comment by corner82** [comment]
ok no problem, I will cerate a new page with this specifics, whichever
consultant chooses he can use relavent page for monitoring....

**Comment by corner82** [comment]
2 new pages has been launched, links are below,
http://88.249.18.205:8090/ecoman/isScopingPrjBaseMDF
http://88.249.18.205:8090/ecoman/isScopingAutoPrjBaseMDF,
old pages are on the run too, so consultant may use preferred page,
please test functionality, issue label has been 'waiting for testing'...

**Comment by gmassard** [comment]
Pages or good but need refinement.
On both pages: remove IS project panel
On both page: clear flow categories design
On manual IS page: control that is is working properly.

**Comment by corner82** [comment]
On both pages:  IS project panels has been removed,
On both pages: flow categories design has been changed to 'Flows' and fixed
On manual IS page: it is is working properly for me but if there is an bud issue or something we can see on next weeks hangout and open a new issue for this,

tester can close issue, label has been changed to 'waiting for testing'...

**Comment by corner82** [comment]
Ok I see, I will implement two column sorting od datagrid then...

**Comment by corner82** [comment]
Now datagrid can be sorted for company and flow columns seperately, First the datagrid is being sorted for companies, user can click on flow and company column headers and can change sorting by sending necessaty request to server, screen shot below

![datagridexpand](https://cloud.githubusercontent.com/assets/5053878/6506373/564b9a30-c353-11e4-9ea2-31e1e5d10d3b.png)

tester can close issue...
