### ISSUE TITLE
IS scoping improvement 2: Flow categories left table improvement

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#155]
We need to clarify how it works.
I would like the the user only need to select a flow category at the first level to automatically select all flow that are in the category.

**Comment by corner82** [comment]
User selects only one category and tree node collapses and checks all child nodes, tester can test it, if it's functionality is ok, tester may close issue, label is cahnged to 'waiting for test'

**Comment by gmassard** [comment]
Ok it seems to be working in a more practical way now!
