### ISSUE TITLE
IS scoping improvement 3: Dynamic table with IS potentials improvement

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#156]
On this table, the user need to be able to see all fields related to the data.
This is needed to select a interesting IS potential.

New column need to be add according to the attribute list of each flow, as display in the dataset management page.

**Comment by corner82** [comment]
I will add a new feature to the grid so when you click a button the row
will expand downside and row related data (whatever we determine) will
appear on the table, I'm sending a screen shot to demonstrate the feature..

**Comment by corner82** [comment]
for the first hangout, I may have some questions about this issue too, so changin its label to 'response waiting'..

**Comment by gmassard** [comment]
Discussed with Zeynel on 05.03.15.

**Comment by corner82** [comment]
feature has been launched, tester may close issue, label changed 'waiting for testing'...

**Comment by gmassard** [comment]
Please add the additional columns then developer can close the issue

**Comment by corner82** [comment]
issue closed
