### ISSUE TITLE
IS scoping improvement 4: Visualisation of saved Is potential table improvement

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#157]
![image2_isscoping](https://cloud.githubusercontent.com/assets/9587966/6411357/e809d472-be77-11e4-8557-bb06edaedf17.png)

1. to find the vizualisation of all saved IS potential table is not easy. User needs to click on a very small arrow on the upper right corner. We need to create a clear button called: IS table management
When clicking on it, the table display all the name of existing table. 

2. Name of first column need to be change from "project name" to "IS table name". To avoid confusion with the project name...

3. The Details column is good but this is not enough to manage the potential. User need to be able to click on "Scenario details". Then a new page display, showing all details on material flow involve and allowing user to directly update and modify data.
This will be a direct link with the dataset management page.
The page should look like the following image and display all attribute field from a flow. Lines can be organize like in the Dynamic table with IS potentials. 2 lines, one aside the other should represent on IS opportunity (Line 1, Company 1 Wood input / line 2, Company 2 Wood output)

![image3_isscoping](https://cloud.githubusercontent.com/assets/9587966/6411498/787cd38c-be79-11e4-84c2-77d86f996329.png)

You can based yourself on the following image from SymbioGIS IS potential display screen.

![capture4](https://cloud.githubusercontent.com/assets/9587966/6411522/ab52a296-be79-11e4-9b6f-b36ca11bffba.JPG)

**Comment by corner82** [comment]
1- Is table management button has been created, datagrids have been put into new panels, so visibility has been better, these changes have been made for all  IS pages too,
2-Name of the first column has been changed.
3- For this issue we need to get into some details, for first hangout will be very good to go into details,
if first two topics all right , tester may close issue and open a new issue for 3. topic...

**Comment by gmassard** [comment]
Zeynel will develop it based on 05.03.15 hangouts discussion

**Comment by corner82** [comment]
this issue is for waiting for testing now

**Comment by gmassard** [comment]
Please do refinement according to discussion and open new issues if needed!
I'm closing this one!
