### ISSUE TITLE
CP scoping reference value for KPI calculation

### ISSUE THREAD

**Issue by Ecoxl** [Leadera/ecoman_repo#159]
Hi Tuna
In CP scoping the reference  value for KPI calculation must be entered manual. It also should be possible according to the UC to select the reference value if it already was entered in data set management.
Best Dirk

**Comment by tcgumus** [comment]
Reference value is entered in the allocation form by consultant. In dataset management there is no field for reference value. If it is required where should i add it?
Best Tuna

**Comment by catherine-moser** [comment]
Dirk, we don't understand what you mean, please precise.
Best Catherine and Tuna

**Comment by catherine-moser** [comment]
covered with another issue. i'll close it.
