### ISSUE TITLE
IS auto page dynamic table sorting

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#166]
IS auto page dynamic table sorting will be set to flows column for Ascending

**Comment by corner82** [comment]
IS auto and manual pages dynamic table sorting  set to flows column for Ascending, rest services has been changed slightky too, tester may close issue..

**Comment by gmassard** [comment]
Implement alphabetical order also for the "company flow sets" table.

**Comment by corner82** [comment]
Alphabetical order also for the "company flow sets" datagrid has been implemented. tester can close issue...

**Comment by gmassard** [comment]
Hi Zeynel. Thank you for implementation.
Actually, I was meaning that first "Company" should be in alphabetical order, then "Flow"
We should have
Geneva 1 - Aluminium
Geneva 1 - Concrete
Geneva 2 - Aluminium
Geneva 3 - Phosphate

**Comment by corner82** [comment]
sorry wrong issue posted earlier

Ok I see, I will implement two column sorting od datagrid then...

Now datagrid can be sorted for company and flow columns seperately, First the datagrid is being sorted for companies, user can click on flow and company column headers and can change sorting by sending necessaty request to server, screen shot below
![datagridexpand](https://cloud.githubusercontent.com/assets/5053878/6506433/c2f8970a-c353-11e4-9fcb-06a27a56e104.png)




datagridexpand

tester can close issue...

**Comment by gmassard** [comment]
Ok for version 1. Thank you!
