### ISSUE TITLE
GIS: display project companies on map

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#171]
http://88.249.18.205:8090/ecoman/project/37

All companies related to the project should appear directly on the existing map.
The "Show companies on map button" can be remove.
Add button to link this map with the full GIS framework.

**Comment by gmassard** [comment]
Developer will suggest features for full GIS framework implementation during my absence!
Developer is able to do its own testing during my absence!

**Comment by gmassard** [comment]
This issue is still open! The map appearing on the main page does not display all companies of the projet.
Also the "See project companies on map" still exist. Clinking on it display a satellite map of Ankara and request errors such as.. Notice: Undefined index: prj_id in C:\xampp\htdocs\IS_OpenLayers\map_prj.php on line 16
Issue not solve at all!

**Comment by emilyvuylsteke** [comment]
Here is a print screen for more details:
![image](https://cloud.githubusercontent.com/assets/10558805/7429811/cfc7c168-f008-11e4-9841-8c54621d5347.png)

**Comment by corner82** [comment]
project page design has been changed and a new map page to show companies on map has been prepared, here is a screen shot of new page,

![silinecek](https://cloud.githubusercontent.com/assets/5053878/7451422/2ad00942-f259-11e4-97e1-625063a5d5c5.png),

Please test and confirm

**Comment by corner82** [comment]
label changed to 'waiting for testing'

**Comment by emilyvuylsteke** [comment]
Indeed the map opens fine now! Thanks! 
One detail: if I open the company map of "geneva test 3" project for example, the map is zoomed on the Turkish companies only. There are some companies in Switzerland but you have to un-zoom the map to see them. Can the Zoom be defined to integrate all companies? Thanks in advance!!

**Comment by emilyvuylsteke** [comment]
This is still not working (eg with geneva test 2, the turkish company integrated in the project does not appear on the map initially, you have to un-zoom to see it)

**Comment by corner82** [comment]
Yes you have to unzoom it, cause the user has to do something on user interface too, like un*zooming or zooming....cause one of the companies is in turkey and the others are in swistzerlad, I'm closing issue, please be more reasonable on requirements, if you mentiaon an reasonable issue, please add as another issue, thank you
