### ISSUE TITLE
Sub, master datagrid feature will deployed to 'Dynamic table with IS datagrids'

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#174]
'Dynamic table with IS' will be master-sub datagrid extension...relates issue  #156

**Comment by corner82** [comment]
'Dynamic table with IS' will be master-sub datagrid extensions has been implemented and newly written  rest services has been attached to interface, tester may close issue, label changed to 'waiting for testing'

**Comment by gmassard** [comment]
I'm closing it!
