### ISSUE TITLE
Create editable  'IS Scenario Details' datagrid

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#186]
A new datagrid will be displayed on new 'IS Scenarios' page, implementing inline editing featute according to columns, related issue #169

**Comment by corner82** [comment]
'IS Scenario Details' datagrid has been launched, but project coordinators on TOBB does not want to edit company flow data from IS module, so update service has been prepared but not active now, after consensus on partners has been done, service will be opened, tester can see functionality up to a certain level, , klabel changed 'waiting for testing'

**Comment by gmassard** [comment]
Please keep discussing with TOBB to implement it!
