### ISSUE TITLE
CP scoping: Graph Cost environemental impact does not show not a flow

### ISSUE THREAD

**Issue by Ecoxl** [Leadera/ecoman_repo#189]
![graph cost and env impact](https://cloud.githubusercontent.com/assets/9587988/6555705/3e727ede-c668-11e4-9bb2-b24a04bf8072.PNG)

**Comment by tcgumus** [comment]
Hello,
Graph shows processes not flows. As you can see here there is only 1 process as "milling" and graph shows it. I have changed the y-axis values of the system referenced buy i thought seeing the x-axis values from 0 might be useful for multi rectangles graphs.

**Comment by Ecoxl** [comment]
Hello Tuna
You are right. It’s a process not a flow. In reporting I will add probably a chart with the impacts of each flow.
Cheers Dirk

Von: Tuna Çağlar Gümüş [mailto:notifications@github.com]
Gesendet: Montag, 9. März 2015 14:42
An: Leadera/ecoman_repo
Cc: Hengevoss Dirk
Betreff: Re: [ecoman_repo] CP scoping: Graph Cost environemental impact does not show not a flow (#189)


Hello,
Graph shows processes not flows. As you can see here there is only 1 process as "milling" and graph shows it. I have changed the y-axis values of the system referenced buy i thought seeing the x-axis values from 0 might be useful for multi rectangles graphs.

**Comment by tcgumus** [comment]
OK. Please close this issue. We can open a new issue for reporting.
