### ISSUE TITLE
CP scoping allocation page: accuracy rate callulation should be changed 

### ISSUE THREAD

**Issue by Ecoxl** [Leadera/ecoman_repo#190]
A high accuracy rate of e.g. 90%  means that the error range is 10%
A low accuracy rate of e.g. 10%  means that the error range is 90%
 Change of calcualtion is required. User enter 90% System calulates with 10%.

**Comment by tcgumus** [comment]
ok i will change it asap :+1:

**Comment by tcgumus** [comment]
Hello, I have changed the code. Now we are calculating error_rate from accuracy_rate value. You can test it in allocation page and "view cp potential identification" page. You will also see accuray_rate value in a blue box (instead of red error_rate value) next to the given value.

**Comment by catherine-moser** [comment]
Calculation is correct. issue can be closed.
I suggest to add an explanation in a box that only opens when the mouse pointer is on the word "accuracy rate".

![image](https://cloud.githubusercontent.com/assets/11196956/6754906/ec38f3bc-cf1f-11e4-99a3-d4321d016b15.png)

**Comment by tcgumus** [comment]
can you open this suggest as a new issue? thank you

**Comment by catherine-moser** [comment]
Hi Tuna

Of course i will open a new issue for this. can we do it together via hangout? i'll share my screen and you can show me how to add labels to issues?

Catherine

------------------------------------------------------------
Fachhochschule Nordwestschweiz FHNW
Hochschule für Life Sciences
Institut für Ecopreneurship

Dipl. Ing. FH Catherine Moser
Wissenschaftliche Mitarbeiterin
Gründenstrasse 40
CH-4132 Muttenz
------------------------------------------------------------
T +41 61 467 44 71
catherine.moser@fhnw.ch
www.fhnw.ch/hls/iec
-------------------------------------------------------------------------

Von: Tuna Çağlar Gümüş [mailto:notifications@github.com]
Gesendet: Sonntag, 22. März 2015 15:19
An: Leadera/ecoman_repo
Cc: Moser Catherine
Betreff: Re: [ecoman_repo] CP scoping allocation page: accuracy rate callulation should be changed (#190)


can you open this suggest as a new issue? thank you
