### ISSUE TITLE
Turkish labels on datagrid

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#198]
Some turkish labels on IS datagirds will be removed

**Comment by corner82** [comment]
Turkish labels on datagrids has been removed, tester may close issue

**Comment by gmassard** [comment]
I just tested it but labels seems still to be in Turkish..

**Comment by emilyvuylsteke** [comment]
This issue has been solved. Thank you. It can be closed.

**Comment by corner82** [comment]
issue closed
