### ISSUE TITLE
Is scenario page 'Scenario name' display on 'Scenario details datagrid' toolbar

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#199]
When double click on 'IS scenarios ' datagrid row , Is scenario page 'Scenario name'  will display on 'Scenario details datagrid' toolbar

**Comment by corner82** [comment]
IS scenario name displayed 'Scenario details datagrid' toolbar , tester can close issue

**Comment by emilyvuylsteke** [comment]
This issue seems to have been solved. Thank you very much. It can be closed!

**Comment by corner82** [comment]
issue closed...
