### ISSUE TITLE
dataset managemnt link from IS pages

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#200]
On IS scenarios and IS detection pages , link to dataset management pages will be preserved on datagrids

**Comment by corner82** [comment]
Dataset managemnt link added to datagrids on 'IS scenarios' page lower datagrid, 'Manual IS detection ' 
page  , 'Dynamic table with IS potentials' datagrid and 'Automated IS detection '  page 'Dynamic table with IS potentials'  datagrid, tester can close issue, label changed to 'waiting for testing'

**Comment by emilyvuylsteke** [comment]
The Dataset Management links have indeed been added in the above mentioned pages. Thank you for this! This issue can be closed.
