### ISSUE TITLE
IS scenarios page datagrid columns

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#201]
On IS scenarios page , lower datagrid column names will be fixed

**Comment by corner82** [comment]
On IS scenarios page , lower datagrid column names has been fixed , tester may close issue, label changed to 'waiting for testing'

**Comment by emilyvuylsteke** [comment]
This issue is solved. Thank you. It can be closed.

**Comment by corner82** [comment]
issue closed
