### ISSUE TITLE
On IS scenarios page, datagrid column changes

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#202]
On IS scenarios page, on the lower datagrid, substitution,potential, description,comments, quality, quantity and unit fields will be added as datagrid columns ,
P.S: 'potential' column could not be found on database table , alike column  'potential_energy'  is on database table and is already being shown on datagrid

**Comment by corner82** [comment]
Additional columns has been displayed on datagrid and all columns has been featured as editable,
tester may close issue

**Comment by emilyvuylsteke** [comment]
This issue seems solved. Just one detail: did you wanted to add "substitution" and "potential" or "substitute potential" ? These are two different things. Currently, the " substitute potential" column has been added.

**Comment by emilyvuylsteke** [comment]
I am guessing this is correct.. Please confirm

**Comment by corner82** [comment]
On ECOMAN database only 'substitute potential' coulumn and data is being saved, so if this approach is not correct that is another issue and important fundemantal issue, I think another issue has to be opened if there is a problem on analysis, so if this issue fullfilled, please close issue...

**Comment by emilyvuylsteke** [comment]
ok seems good. This issue can be closed.
