### ISSUE TITLE
On IS detection detail datagrids  columns modification

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#203]
On IS detection detail datagrids , detail datagrid column names will be fixed

**Comment by corner82** [comment]
on IS detection pages, on 'automated IS' and 'manual IS', detail datagrid columns has modified as asked for, tester may close issue, label changed to 'waiting for testing'

**Comment by emilyvuylsteke** [comment]
This has been solved. Than you! It can be closed

**Comment by corner82** [comment]
issue closed
