### ISSUE TITLE
IS detection detail datagrids new columns will be added, service layer will be extended

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#204]
On IS detection detail datagrids substitution,potential, description,comments, quality, quantity fields will be added 
P.S: 'potential' column could not be found on database table , alike column 'potential_energy' is on database table and is already being shown on datagrid

**Comment by corner82** [comment]
tester  may close issue

**Comment by emilyvuylsteke** [comment]
This issue seems solved. Just one detail: did you wanted to add "substitution" and "potential" or "substitute potential" ? These are two different things. Currently, the " substitute potential" column has been added. I am guessing this is correct.. Please confirm

**Comment by corner82** [comment]
I'm typing the same answer as for #202,

On ECOMAN database only 'substitute potential' coulumn and data is being saved, so if this approach is not correct that is another issue and important fundemantal issue, I think another issue has to be opened if there is a problem on analysis, so if this issue fullfilled, please close issue...

**Comment by emilyvuylsteke** [comment]
Same answer than for issue 202. This seems to be good. I will close this issue.
