### ISSUE TITLE
On 'Automatic IS detection' page map display

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#205]
On 'Automatic IS detection' page , map will be displayed in the page , not on another window

**Comment by corner82** [comment]
On 'Automatic IS detection' page, a new map page has been diplayed on page, page layout has been changed to show map embedded on page, tester mat close issue, label changed 'waiting for testing'

**Comment by emilyvuylsteke** [comment]
The map has been embedded on page, thank you!
But:
1. The companies of the project does not appear on the map. I would be good to do so, so the map is usefull for the user.
2. When scrolling down to the map, once the "mouse" is on the map, the zoom functionality takes over to the scrolling function. Then the user has a very low navigability. We need to improve this.

**Comment by emilyvuylsteke** [comment]
Is it ok for you if I remove the "waiting for testing" label when a new request is made?

**Comment by corner82** [comment]
I think, if taht specific feature has been implemented, better to open new issue and relate new issue with the old one, for me it is easier to follow up new developemntes and requirements

**Comment by emilyvuylsteke** [comment]
ok I will do this for future issue if the request is not to much linked to the previous issue.

**Comment by corner82** [comment]
Please refer to my screen shots and project for testing issues, cause we can test these pages for months, thanks

**Comment by emilyvuylsteke** [comment]
I think this issue is not relevant anymore, as we decided to remove the map initially embedded in the "automated IS" page. I will therefore close this issue
