### ISSUE TITLE
On 'Manual IS detection' page layout and functionality for map display

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#206]
On 'Manual IS detection' page layout and functionality for map display  will be changed to embedd map on page

**Comment by corner82** [comment]
NEw layout has been set, map panel opens only when the user wants too see IS data on map, also ''close map' button has been added to toolbar, tester may close issue

**Comment by emilyvuylsteke** [comment]
As specified in issue 274, I cannot for the moment generate a IS scenario, so I cannot test this issue. I will wait for the issue 274 to be solved before being able to test this issue.

**Comment by emilyvuylsteke** [comment]
To be more precise, it is not that I cannot generate a scenario but more that the IS potential does not appear in the right lower panel. Therefore it cannot be selected and I cannot ask to visualize the map.

**Comment by corner82** [comment]
Please refer to my screen shots and project for testing issues, cause we can test these pages for months, thanks

**Comment by emilyvuylsteke** [comment]
I will close this issue as it seems solved.
