### ISSUE TITLE
IS detection pages (both auto and manual) main datagrid editable feature

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#207]
IS detection pages (both auto and manual) main datagrid will be editable

**Comment by corner82** [comment]
both datagrids editable feature implemented, but service layer will be activated after update possible flaws and data integrity precautions has been discussed in detail, tester may test interface functionality , label changed 'waiting for testing'

**Comment by emilyvuylsteke** [comment]
Thank you!
Edit button in implemented and seems to work. Not possible to test data edition for now to not challenge data integrity in the database.
We should leave this issue open until the database is editable and test again the functionality afterwards.
