### ISSUE TITLE
GIS framework integration

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#209]
GIS framework will integrated into codeIgniter framework

**Comment by corner82** [comment]
First integration goals has been achieved, , links will be put inside project pages by Mr.Tuna, tester may test issue

**Comment by gmassard** [comment]
First integration seems to be successfull!
However, the framework display only the map of Ostim. We need to center the map on the open project location directly.
Also, text on the right is in Turkish. Would is be possible to add some english text to explain what can be done with the framework for users to understand?

**Comment by emilyvuylsteke** [comment]
We should discuss with Guillaume on friday if this issue needs to be tackled for version 1

**Comment by corner82** [comment]
what do you mean for version 1 discussion, for version 1 things to be done alradey discussed, I will close issue, thanks
