### ISSUE TITLE
Add error report when flow exists already in dataset

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#211]
If you enter a flow name that already exists for this company and click "add flow" you get no error prompt, but the new data is lost as the existing flow is not changed. The system should prompt an error message "Flow name already exists, please choose another name or edit existing flow". The entered data (quantities etc.) should be temporarily saved, so the user only needs to change the flow name.

I'll add labels to this issue as soon as I know how to do that...

**Comment by tcgumus** [comment]
Now system gives an error when you try to insert an already inserted flow. 
![image](https://cloud.githubusercontent.com/assets/2714346/6867547/e0fbcce2-d48b-11e4-83b3-32fdf2a076a2.png)

**Comment by catherine-moser** [comment]
thank you, issue can be closed
