### ISSUE TITLE
CP Scoping: Add name to reference and add definition of KPI

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#213]
A possibility to add a name to the reference would be useful. e.g like this: 

![image](https://cloud.githubusercontent.com/assets/11196956/6752949/bb066f70-cf12-11e4-93ce-1c79fa7dc306.png)

**Comment by tcgumus** [comment]
where can i display this comment? thank you :+1:

**Comment by catherine-moser** [comment]
i suggest to make the field reference shorter so there is room for a comment.

Now it looks like this:
![image](https://cloud.githubusercontent.com/assets/11196956/6799096/48c35b90-d213-11e4-971b-447f72c251ab.png)


and new it would look like this
![image](https://cloud.githubusercontent.com/assets/11196956/6799104/539fa8c0-d213-11e4-99e4-e4d9dbce3de2.png)

Did that answer you question?

**Comment by catherine-moser** [comment]
Please don't use the word "comment" use the word "name of reference flow" (see also issue ???)

**Comment by tcgumus** [comment]
Ok but this is the allocation page right? When allocation completed you wont see this page. You will see cp scoping pages. What i asked was where i will display this field in the cp scoping pages. For example cp scoping main page, kpi calculation page. What is this comment for? We have already comment for every dataset data and kpi calculation pages. We have also comment section for cp scoping calculated data.

**Comment by catherine-moser** [comment]
good idea: the data is ENTERED on the allocation page and also DISPLAYED also on the KPI calculation page.
To name the new field "comment" was a bad choice from my side. it should be named "name of reference flow". Like this the user can see easily how the KPI was defined (I think the definition of the KPI is very important and should be visible).
I made an example:
CP allocation page
![cp allocation](https://cloud.githubusercontent.com/assets/11196956/7386488/f6dfb2a2-ee54-11e4-965e-6ad44efba0e6.PNG)

KPI calculation page
![kpi calculation](https://cloud.githubusercontent.com/assets/11196956/7386469/a3f417a4-ee54-11e4-9523-15061266db58.PNG)

**Comment by tcgumus** [comment]
Did it now. Can you check?

**Comment by tcgumus** [comment]
Added name of reference to new allocation page and edit allocation page
Added kpi definition to new allocation page and edit allocation page
Added kpi definition to KPI calculation table
Made necessary language support.

commit 99527093f0f963adf77d53846b08db2c4d6624e0

**Comment by catherine-moser** [comment]
Hi
I imagined that the KPI definition would be generated automatically from the entered data. But this is not a must, only a nice (prio 2).
![image](https://cloud.githubusercontent.com/assets/11196956/9574930/ce8574d0-4fcb-11e5-9c92-711bec360faf.png)

**Comment by catherine-moser** [comment]
can you please also change the title of the graphic? (marked red)
![a3f417a4-ee54-11e4-9523-15061266db58](https://cloud.githubusercontent.com/assets/11196956/9575238/4741089c-4fce-11e5-9cbb-1c5cfb42eb33.PNG)

**Comment by catherine-moser** [comment]
see also #248 regarding the graph

**Comment by tcgumus** [comment]
I have changed. can you test it?

**Comment by catherine-moser** [comment]
ok thanks. I will close this issue and open a new one (low priority) for the automatisation of the KPI definition. Now this field is not "used" everywhere, right?
