### ISSUE TITLE
Map framework look and feel change

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#215]
Map framewrk components will look like easyui components

**Comment by corner82** [comment]
map framework extjs components look and feel has changed as easyui components, tester may close issue

**Comment by emilyvuylsteke** [comment]
Is this issue linked to the GIS framework?
Please explain what needs to be tested.

**Comment by corner82** [comment]
GIS framework work is totally different from indivigual map displays, Our GIS framework look and feel was a liitle different from other modules, so for the first version all GIS framework code has been put on codeigniter framework code and look and feel has been chenged to look like other modules, so answer is yes you can check look and feel

**Comment by emilyvuylsteke** [comment]
By "look and feel" do you mean the layout of the map? the aim was to make the layout and the use of the map similar to the other maps in ECOMAN?

**Comment by corner82** [comment]
Yes the layout , menus and similarity with other pages....

**Comment by gmassard** [comment]
O, I tested the issue.
