### ISSUE TITLE
new dropdown for IS scenarios save popup

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#217]
New dropdown for IS scenarios save popup will be implemented for 'IS scenarios status' data

**Comment by corner82** [comment]
New dropdown for IS scenarios save popup has been be implemented for 'IS scenarios status' data , for both 'IS auto' and 'IS manual' pages, tester may close issue

**Comment by emilyvuylsteke** [comment]
The IS scenarios status refers to the IS Scenarios (supervisors) page?
http://88.249.18.205:8090/ecoman/isscenarios#

Can you explain where the "status" colomn is?
Also, what is the relation between "IS Project Details" table and the "IS Project Edit Details" table?

**Comment by corner82** [comment]
no, this dropdown is on the 'IS scenario save'  popup, so I'm sending screen shot below,

![silinecek](https://cloud.githubusercontent.com/assets/5053878/7453526/e38d0732-f272-11e4-8a32-26ef8a0493ea.png)

**Comment by emilyvuylsteke** [comment]
Ok. this works fine. I will close the issue
