### ISSUE TITLE
Service modification for IS scenario insert (IS scenario status data)

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#219]
Service modification for IS scenario insert function for 'IS scenario status'  data

**Comment by corner82** [comment]
Service modification for IS scenario insert function for 'IS scenario status' data has been implemented and tested, tester may close issue

**Comment by emilyvuylsteke** [comment]
Hi,
What to you mean by service modification?
Also, can you point us where the "IS scenario status" data or field has been inserted?

**Comment by corner82** [comment]
That service modification is totally developers work, 'IS status ' dropdown is this dropdown is on the 'IS scenario save' popup, so I'm sending screen shot below, I tried to expalin it on the issue #217, screen shot below,

![silinecek](https://cloud.githubusercontent.com/assets/5053878/7453611/adca86be-f273-11e4-9d30-ae20155ca896.png)

**Comment by emilyvuylsteke** [comment]
Ok. I will close this issue
