### ISSUE TITLE
New Is scenarios page for only consultants

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#221]
IS scenarios page for only consultants will be prepared

**Comment by corner82** [comment]
New page for only consultants(not supervisors) has been launched, tester may close issue

**Comment by emilyvuylsteke** [comment]
Thank you for implemented this page. This page should be tested again when user rules have been specified in more details. We should leave this issue open until then.

**Comment by gmassard** [comment]
Hi Zeynel, where do we stand with this issue? What is the difference between IS scenario for consultant and for supervisor page?
What is your next steps related to this issue?
