### ISSUE TITLE
Line between companies and zoom function for the IS scenario map

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#236]
Both IS scenario pages (for supervisors and consultant pages) , IS project map will be embedded inside the pages

**Comment by corner82** [comment]
IS project map has  been  embedded inside the pages, tester may close issue

**Comment by emilyvuylsteke** [comment]
The map of the IS scenario opens fine. Thank you.

Some details: 
- Should there not be line(s) between the two companies, with some indications on the exchanged flows ?
- Could the "close map" button be on the map itself and not on top of the IS scenario panel? 

Thanks in advance!

**Comment by emilyvuylsteke** [comment]
for info, the "close map" button issue can be for version 1.2. Still, the "line" issue must be solved

**Comment by emilyvuylsteke** [comment]
Also, the zoom function for this map is addressed in issue number 281.

**Comment by emilyvuylsteke** [comment]
I will close this issue and open news specific issues on the matter.
