### ISSUE TITLE
CP Scoping: Database error

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#237]
Hi
I typed this in 
![image](https://cloud.githubusercontent.com/assets/11196956/6804424/d20822bc-d23d-11e4-9f38-a2d3547a004d.png)

and got this error
![image](https://cloud.githubusercontent.com/assets/11196956/6804399/ad98b64e-d23d-11e4-9374-001416339279.png)

I tested, the minus is not the problem.

**Comment by tcgumus** [comment]
can you please try again.?

**Comment by catherine-moser** [comment]
ok

------------------------------------------------------------
Fachhochschule Nordwestschweiz FHNW
Hochschule für Life Sciences
Institut für Ecopreneurship

Dipl. Ing. FH Catherine Moser
Wissenschaftliche Mitarbeiterin
Gründenstrasse 40
CH-4132 Muttenz
------------------------------------------------------------
T +41 61 467 44 71
catherine.moser@fhnw.ch
www.fhnw.ch/hls/iec
-------------------------------------------------------------------------

Von: Tuna Çağlar Gümüş [mailto:notifications@github.com]
Gesendet: Dienstag, 24. März 2015 16:18
An: Leadera/ecoman_repo
Cc: Moser Catherine
Betreff: Re: [ecoman_repo] CP Scoping: Database error (#237)


can you please try again.?

**Comment by catherine-moser** [comment]
ok, now it worked! you can close the issue.
