### ISSUE TITLE
admin report page will be prepared

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#241]
Report create, update and dispaly page will be prepared, all functionalities will be in one page and servre side processes will be handled by rest service layer and jasper report server layer

**Comment by catherine-moser** [comment]
where can I find it for testing?
Catherine

**Comment by corner82** [comment]
Hi Catherine,
new page has been prepared, user must be logged in to see report page, page link http://88.249.18.205:8090/ecoman/admin/report developer closing issue, related issue #243

**Comment by catherine-moser** [comment]
Hi Zeynel
i'm testing now. should i open seperate issues for my comments or comment only in this issue?
Catherine

**Comment by corner82** [comment]
if the comment is about a bug or fix please use the same issue, for new
features maybe we should open new issues, and relates issues to each other
if necessary, thanks...

**Comment by catherine-moser** [comment]
ok, thanks for the quick response.

**Comment by catherine-moser** [comment]
Confidentiality:
- i can look at already created reports from all companies --> I should only see data from MY companies
- i can even create reports for all companies

**Comment by catherine-moser** [comment]
oops. closed "report" window by cklicking on cross like in "reports datagrid" window, now no reports are  displayed anymore...
![image](https://cloud.githubusercontent.com/assets/11196956/7249393/4e525ca6-e81a-11e4-820c-36794f46d1a6.png)

**Comment by catherine-moser** [comment]
Spelling mistake:
![image](https://cloud.githubusercontent.com/assets/11196956/7249456/cae34366-e81a-11e4-93a3-03cdddd9d32e.png)

**Comment by corner82** [comment]
Hi, as for "Confidentiality" issue,
This page is designed for admin user for admin pages, further pages will be prepared as needed for consultant use only....

**Comment by catherine-moser** [comment]
ok.

**Comment by kuisatz** [comment]
Hi Catherine. 
Corrected typos.

**Comment by corner82** [comment]
Hi Catherine,
as for 'mistakenly closing panel' problem, all "close panel buttons" has been removed,  you can check it out

**Comment by catherine-moser** [comment]
the report panel still has one and if I klick it, i can't see any reports or get the panel back.

![image](https://cloud.githubusercontent.com/assets/11196956/7250528/6b365350-e823-11e4-9391-2a2c2cf95fe3.png)

**Comment by catherine-moser** [comment]
missing information:
•	Consultant info: Name of agency, name of consultant, Address, Logo 
•	Time period that the report is covering
•	Date of report generation

**Comment by catherine-moser** [comment]
can see new reports even tough system claims to have created them:
![image](https://cloud.githubusercontent.com/assets/11196956/7250960/dd5dc2f8-e826-11e4-863a-78ead30dcbd8.png)

**Comment by catherine-moser** [comment]
i ticked all attributes for flows, but they are not shown in the report:
![image](https://cloud.githubusercontent.com/assets/11196956/7251010/48d210a2-e827-11e4-8987-ee92472595aa.png)

![image](https://cloud.githubusercontent.com/assets/11196956/7251016/56298a1e-e827-11e4-9f8c-0165947a15db.png)

**Comment by corner82** [comment]
Lsst panel "remove button" has been removed, check it out , please....

**Comment by catherine-moser** [comment]
yes, thanks!

**Comment by catherine-moser** [comment]
please display all numbers right-aligned in stead of centered, it's easier to read/compare.
![image](https://cloud.githubusercontent.com/assets/11196956/7251180/3c50e9b4-e829-11e4-90b3-7165f209d613.png)

**Comment by catherine-moser** [comment]
could you also add the thousands separator? (e.g. 76'800.00 instead of 76800.00) also makes it easier to read.

**Comment by catherine-moser** [comment]
The Flows and Components are not yet in the order as intended:

![image](https://cloud.githubusercontent.com/assets/11196956/7251376/37048fe0-e82b-11e4-8a31-e635435a4c5b.png)

![image](https://cloud.githubusercontent.com/assets/11196956/7251383/4872320a-e82b-11e4-9bef-f50ccae5583d.png)

![image](https://cloud.githubusercontent.com/assets/11196956/7251388/50533618-e82b-11e4-86f7-c66b765ee30f.png)

**Comment by catherine-moser** [comment]
- please add units to rates of utilitsation.
- where does the "1" come from?
![image](https://cloud.githubusercontent.com/assets/11196956/7251482/33ef36f6-e82c-11e4-98d6-bedf427a7c7e.png)

**Comment by corner82** [comment]
as for "missing information" problem,
"Consultant info: Name of agency, name of consultant, Address, Logo "
      Consultan name and surmname is being displayed at data grid, but there is no any  "consultant agency data" any where on ecoman project overall :)

![dddd1](https://cloud.githubusercontent.com/assets/5053878/7251527/d9f17020-e834-11e4-9615-da5d1fe975db.png)

"Time period that the report is covering"
at report use case any time period has not been mentioned earlier as I remember, so the queries and report data and also at ecoman overalll none of the data has time period,

" Date of report generation"
date of time period has been put on datagrid as shown below,

![dddd1](https://cloud.githubusercontent.com/assets/5053878/7251597/91fedb12-e835-11e4-9899-679f2a26f0ac.png)

**Comment by catherine-moser** [comment]
i have a meeting now, will check it out later.

**Comment by kuisatz** [comment]
This report was developed as a summary report.
unfortunately it create problems in the structure on the report wizard,when all flow fields and other features are in the same report 
therefore we need to create a detailed separate report of the flow chart

**Comment by catherine-moser** [comment]
ok, i will talk to Dirk about this.

**Comment by catherine-moser** [comment]
Missing data:
- Consultan name and surmname is being displayed at data grid, --> needs to be on the printable report as well.
- date of time period has been put on datagrid as shown below, --> needs to be on the printable report as well.
- but there is no any "consultant agency data" any where on ecoman project overall :) --> I will address this in a separate issue :-) (low priority)
- at report use case any time period has not been mentioned earlier as I remember, so the queries and report data and also at ecoman overalll none of the data has time period, --> as far as I know this has been discussed. I will talk to Dirk about it.

**Comment by catherine-moser** [comment]
Summary report:
i talked to Dirk about this. For this version it's ok if there are 2 reports, one summary, one detailed for the flows. we will see if this works out, if not we will see what we can do about it in the next version.

**Comment by catherine-moser** [comment]
issues that need NO further work:
to "reports not found": found them now :-)
to "consultant on report": ok, thanks!
To "right aligned and thousands separator: ok, thanks!

issues that NEED further work:
to "generation date on report": Typo: it's "creation date"
to "sorting": not sure if you worked on this, still not in the intended order
To "add units to rates of utilitsation": not sure if you worked on this, still not all units printed

if you fix the sorting and / or unit problem, please leave a short message here so I can test. Thanks, Catherine

**Comment by kuisatz** [comment]
Hi Catherine.
Corrected typos.
 "creation date" 

![1](https://cloud.githubusercontent.com/assets/8280491/7391510/6fa7479c-ee8a-11e4-9c31-aad8b2211162.png)

**Comment by kuisatz** [comment]
i will check for "sorting" and "units"

**Comment by kuisatz** [comment]
"see flow details" column has been added to the reports datagrid 
you can find the flow detail report there

**Comment by catherine-moser** [comment]
For the missing reports: i know now why i couldn't find them in the first place: The navigation (see 2nd picture) is not always visible.
![image](https://cloud.githubusercontent.com/assets/11196956/7490144/1ea4dc5c-f3de-11e4-87ab-c69b045c80e3.png)

![image](https://cloud.githubusercontent.com/assets/11196956/7490152/34266b4a-f3de-11e4-8123-22b3f6c04846.png)

**Comment by catherine-moser** [comment]
Flow detail report:
thank you, I only have 1 comment:
Please write "available" respectively "not available" instead of "true"/"false" for the availability
![image](https://cloud.githubusercontent.com/assets/11196956/7490302/54a38852-f3df-11e4-97ec-9a1f7c19ae6f.png)

**Comment by kuisatz** [comment]
Hi Catherine. 

Flow detail report:   availability  changed

**Comment by catherine-moser** [comment]
i can't see the flow details of my company. always the same report comes up no matter what I do.
![image](https://cloud.githubusercontent.com/assets/11196956/7510974/b3f31e40-f4a1-11e4-93e8-68a85bb9c5cd.png)

**Comment by kuisatz** [comment]
ups :) 
ok done

**Comment by catherine-moser** [comment]
ok but:
- not all attributes are reported (e.g output location)
- the attributes are reported if i tick the box or not
- Typo: pression should be pressure
- if no data is entered the field should be empty and not 0
![image](https://cloud.githubusercontent.com/assets/11196956/7512672/d4f315b6-f4ae-11e4-84c1-e1abb116c3c9.png)

**Comment by kuisatz** [comment]
all  done .. :) 
check pls

**Comment by catherine-moser** [comment]
:-)
![image](https://cloud.githubusercontent.com/assets/11196956/7517338/bfc8fbd0-f4d4-11e4-8ac4-0b0ded22c5d9.png)

**Comment by catherine-moser** [comment]
The tickboxes are not working properly. Test-Scenario:
i open an existing detailed report
![image](https://cloud.githubusercontent.com/assets/11196956/7517432/3f6b8a4c-f4d5-11e4-8925-ca0ab9ed736d.png)
i go to the tickboxes
![image](https://cloud.githubusercontent.com/assets/11196956/7517440/4b0e1afe-f4d5-11e4-817f-773456754dc1.png)
and add ticks and press update
![image](https://cloud.githubusercontent.com/assets/11196956/7517464/7c86b226-f4d5-11e4-947a-bb295a27b659.png)
i get the success message
![image](https://cloud.githubusercontent.com/assets/11196956/7517477/907e0086-f4d5-11e4-8ed5-ed4bbe7ba269.png)
BUT the report is still the same
![image](https://cloud.githubusercontent.com/assets/11196956/7517495/a926f61a-f4d5-11e4-88cf-809104b30346.png)
i try to refresh the page
now the window is empty...
![image](https://cloud.githubusercontent.com/assets/11196956/7517535/d8b7343a-f4d5-11e4-8d9f-e6af4801f60c.png)

**Comment by kuisatz** [comment]
select report pls ..

**Comment by catherine-moser** [comment]
does not help!
![image](https://cloud.githubusercontent.com/assets/11196956/7517671/b0dfe83e-f4d6-11e4-8c8f-02c14d47432d.png)
![image](https://cloud.githubusercontent.com/assets/11196956/7517680/babe5b42-f4d6-11e4-94a5-6a717149998f.png)

**Comment by kuisatz** [comment]
which one ? 


![qw](https://cloud.githubusercontent.com/assets/8280491/7518316/e3e95290-f4e2-11e4-89ae-ea1699ae309f.png)

**Comment by catherine-moser** [comment]
sorry bad example :-)
i klick edit
![image](https://cloud.githubusercontent.com/assets/11196956/7518421/14797e4c-f4db-11e4-9ad1-b34e90dab63b.png)
i add ticks and klick update
![image](https://cloud.githubusercontent.com/assets/11196956/7518428/2ab87910-f4db-11e4-9618-36aaeb99bc41.png)
get succes message, but...
![image](https://cloud.githubusercontent.com/assets/11196956/7518438/3f6d8e7c-f4db-11e4-8152-58f42d00ba9d.png)
attributes still not displayed.

**Comment by catherine-moser** [comment]
i'll be back for testing on Monday!

**Comment by kuisatz** [comment]
first you need to chose the "update report" and then click the "see report details" which you can find in the "report details" for your chosen report
i think you only need to click the "update report" button.

   1 - click "Edit"
   2 - select "report attributes"
   3 - click "update report"
   4 - click "see report details"

**Comment by catherine-moser** [comment]
ok i understand now why there was a misunderstanding:
i thought the success message meant the report was updated. but I still need to click "see flow details" AGAIN to really see the updated report. can't this be automated?
https://cloud.githubusercontent.com/assets/11196956/7517477/907e0086-f4d5-11e4-8ed5-ed4bbe7ba269.png

**Comment by catherine-moser** [comment]
also some attributes are always displayed (in accordance with use case). can the ticks be fixed there?
![image](https://cloud.githubusercontent.com/assets/11196956/7566614/1b0f3920-f7f8-11e4-84ac-b9737ec57901.png)

could the attributes be sorted in the same order as they are presented in the report? also then all the "fixed" attributes would be at the top.

**Comment by catherine-moser** [comment]
Hi Okan
any progress on "sorting"?
Catherine

**Comment by catherine-moser** [comment]
Hi Zeynel
Why did you close this issue? Is the reporting module finished? can I test it?
Best, Catherine
