### ISSUE TITLE
KPI View and Edit Table page Version 1.0

### ISSUE THREAD

**Issue by Ecoxl** [Leadera/ecoman_repo#248]
titel of y-axis should be  "% of Benchmark KPI"
red field should be renamed to "Exceed Benchmark-KPI"
green field should be renamed to "Better than Benchmark-KPI"

**Comment by catherine-moser** [comment]
also 
Blue field should be renamed to "Current company KPI"
title of x-axis should be renamed to "Process name": "Flow name" / "Reference name"
in consequence a name for the reference has to be introduced in CP Allocation page as proposed in issue ??.
(Like this the calculation of the KPI (= Flow amount divided by Reference) is quickly visible.)

**Comment by catherine-moser** [comment]
The problem with the current graph is, that there is no accurate name for the blue bar. Therefore I suggest to change the graph like in this example
![diagramm-pgc04](https://cloud.githubusercontent.com/assets/11196956/8230301/3b402f30-15bf-11e5-9ea1-ab30867c7ca5.jpg)
(of course the color red and green would be the other way around in our example and als the colored bars would start or stop at 100%).
Like this we can name the blue (grey in the example) bar "Company KPI value".

**Comment by tcgumus** [comment]
![screen shot 2015-07-06 at 15 22 30](https://cloud.githubusercontent.com/assets/2714346/8522958/d6e360ce-23f2-11e5-9e38-2e0ba19790a4.png)
We decided to solve this problem by modifying the graph like the picture above.

**Comment by catherine-moser** [comment]
please change %100 to 100%  :-)

**Comment by tcgumus** [comment]
hello, i have fixed the graph as we decided. I can't add a line for "%100" but solved other problems.

**Comment by catherine-moser** [comment]
Hi, I have a few comments:
- titel of y-axis should be "% of Benchmark KPI"
- labeling of columns should be "Process name": "Flow name" / "Reference name"
- please add a key for the colors: red: "Exceed Benchmark-KPI", yellow: "Equal to Benchmark-KPI", green: "Better than Benchmark-KPI"

I also encountered problems with the "see changes" function but I will open a new issue for that.

**Comment by tcgumus** [comment]
i will delete the see changes button. no need to open a new issue for that.

**Comment by catherine-moser** [comment]
already done... #387

**Comment by tcgumus** [comment]
what is the reference name?

**Comment by catherine-moser** [comment]
Hi Tuna
Just talking to Dirk and we agree that the line in the graph "100% = Benchmark" is very important for us. If it helps, you can limit the y-axis to 300% or 500% depending of the readabilty of the graph.

**Comment by catherine-moser** [comment]
Reminder to myself: check pop ups in the graphs.

**Comment by catherine-moser** [comment]
not sure if youre question is still open, but just in case:
Reference name is entered in the allocation page
![image](https://cloud.githubusercontent.com/assets/11196956/9627703/116ee826-5166-11e5-8943-9ba18fa01a4e.png)

**Comment by tcgumus** [comment]
ok. But it is not mandatory so i can be empty for some allocations

**Comment by catherine-moser** [comment]
if the blue field is mandatory also the red should be (i think).
![image](https://cloud.githubusercontent.com/assets/11196956/9627913/beb7dd48-5167-11e5-85d8-dd172e4a6840.png)

**Comment by tcgumus** [comment]
reference field is mandatory. ok then i will also make "name of reference" field mandatory as well.

**Comment by catherine-moser** [comment]
ok

**Comment by catherine-moser** [comment]
regarding the pop up:
I think there is no need to repeat the text thats also labeling the columns but to give the percentage is useful. However I would call it "company performance relative to benchmark" and not give any decimals (e.g. 85% instead of 85.66666%)
i am able to click on a column and then it gets a small white frame but otherwise nothing happens. is that on purpose?
![image](https://cloud.githubusercontent.com/assets/11196956/9628105/02529736-5169-11e5-935f-f73e719466f6.png)

**Comment by tcgumus** [comment]
yes i will change the text but in a case like design texts in the bottom will be stacked so you will need to hover the bar to see which bar it is. I think we shouldn't delete allocation name form hover. Also yes the border is on purpose for the same reason

**Comment by tcgumus** [comment]
![screen shot 2015-09-02 at 15 04 40](https://cloud.githubusercontent.com/assets/2714346/9630583/f949d134-5183-11e5-9db5-300c60d8d5ff.png)

an example from dizayn case-study

**Comment by catherine-moser** [comment]
ok so leave the text in the hover.
but why the white border? it would make sense to me if when I click the white border appears AND the hover stays even if I move the mouse from the column.

**Comment by catherine-moser** [comment]
copy from above:
Just talking to Dirk and we agree that the line in the graph "100% = Benchmark" is very important for us. If it helps, you can limit the y-axis to 300% or 500% depending of the readabilty of the graph.
(i think in the dizayn case the KPIs that exceed the Benchmark 8000% are not valid.)

**Comment by tcgumus** [comment]
name of reference is now mandatory.
graph now shows max value of near 400% but you can see the real difference when you hover the bar.
you will also see the %100 line.
now values will be rounded to nearest number value. so you will see %50 instead of 49.888888777777%
notation : "red: "Exceed Benchmark-KPI"
yellow: "Equal to Benchmark-KPI"
green: "Better than Benchmark-KPI"" for KPI graph added

**Comment by tcgumus** [comment]
changed the text to "company performance relative to benchmark".
made some performance enhancement

**Comment by catherine-moser** [comment]
some details left:
hover: can you add %-sign to the number?
labeling of columns  + hover should be "Process name": "Flow name" / "Reference name"
titel of y-axis can you add KPI --> "% of Benchmark KPI"
white border? it would make sense to me if when I click the white border appears AND the hover stays even if I move the mouse from the column.

**Comment by tcgumus** [comment]
Nope we can't add it.
Labelling is already like this Process name ( Flowname-flowtype / reference name ).
No i can't change the border actions.

**Comment by tcgumus** [comment]
I have changed the yaxis label

**Comment by catherine-moser** [comment]
text in label and hover is not complete. reference name is not shown
![image](https://cloud.githubusercontent.com/assets/11196956/9659009/dd3e9f18-524d-11e5-84a7-b91a95de9e1f.png)

**Comment by tcgumus** [comment]
As i said before "But it is not mandatory so i can be empty for some allocations". Reference name is now empty for older projects. Thats why we made it mandatory now right?. You can update your allocations with reference name and you will see the reference name in graph

**Comment by catherine-moser** [comment]
ah didn't think of that. will continue testing tomorrow

**Comment by catherine-moser** [comment]
all good, thanks!
