### ISSUE TITLE
CP Scoping: Enter Benchmark value

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#251]
Hi Tuna
I can only enter integer values for Benchmark (e.g. 0.5 is not possible). can this be changed?
Thanks, Catherine

![image](https://cloud.githubusercontent.com/assets/11196956/7248829/2ef61fcc-e816-11e4-82f4-cee0cd4d120e.png)

**Comment by tcgumus** [comment]
Now you will be able to enter number with 5 precision at the KPI calculation page.

**Comment by catherine-moser** [comment]
ok, thanks. does it always need to display the 5 zeros after the comma?

**Comment by catherine-moser** [comment]
solved, thanks.
