### ISSUE TITLE
Rate of Utilisations: System doesn't check if minimum < maximum

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#255]
The system does not check if rate of utilisation is minimum < typical < maximum
![unbenannt 2](https://cloud.githubusercontent.com/assets/11196956/7276939/5cf57010-e90d-11e4-9997-dc178a811823.PNG)

**Comment by tcgumus** [comment]
We talked with dirk. System won't check the for the correction for the values entered by the consultant. In this way consultants can do more than one allocation for a flow. So that they can analyse allocation in different layers.
