### ISSUE TITLE
Explanation of term "Qualitative error of estimation"

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#256]
Related to #250

I suggest to add an explanation in a box that only opens when the mouse pointer is on the word "Qualitative error of estimation".

![image](https://cloud.githubusercontent.com/assets/11196956/7296341/efd60c6c-e9be-11e4-8323-6830a79d2aef.png)

**Comment by tcgumus** [comment]
I have added to tooltip at create allocation and edit allocation page. It looks like this. 

![screen shot 2015-05-13 at 15 10 42](https://cloud.githubusercontent.com/assets/2714346/7611144/b02c9882-f982-11e4-9700-605f6e3042f4.png)

**Comment by catherine-moser** [comment]
Thank you!
