### ISSUE TITLE
Create project page improvement

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#258]
Can a “address” box be created and can the address info be use to locate automatically the project on the map? In this way, the user would not need to enter coordinates, that he rarely knows. Also (less important), the “start date” box does not indicate the format of date required. Does that mean all format are accepted (dd/mm/yy ou dd/mm/yyyy ou mm/dd/yy, etc)? I don’t know if the calendar icon should lead to a function or if it is just there as an image, but in case it should lead to a calendar small pop-out to choose the date, it didn’t work for me.

**Comment by catherine-moser** [comment]
i have some more points to this page:
- Typo: PlanNing
- I don't understand the functionality of "zoom level"
- Contact person can't be assigned as it is filled automatically with consultant and companies

![image](https://cloud.githubusercontent.com/assets/11196956/7343746/7a599440-ecc5-11e4-9f38-d9e11d83885f.png)

**Comment by corner82** [comment]
I think this issue is related to, #259 , so I made same comment here....

"There is an available service to get coordinates from adress info from google services, but I'm afraid after 2500 requests per daily it is paid service, so can be implemented but may cause some payment if the program used intensively. Already Okan has prepared a structure to locate country of company automatically from lat, long point information, so it is our choivce to implemet that feature..."

**Comment by emilyvuylsteke** [comment]
Is it possible to implement this service and to follow the rate of use to verify that it does not exceed 2500 request? It will not get to this rate before some time, and we think it is a necessary service to provide to the user.

**Comment by corner82** [comment]
Sure, We can plan this work out for version 1.1

**Comment by emilyvuylsteke** [comment]
Ok. Should I leave this issue open until then or do you have a internal list of things to do for version 1.1?

**Comment by corner82** [comment]
we will determine what will be done for new version witl all partners, so I think version label can be changed to 1.2 and further discussion can be made on this issue.

**Comment by tcgumus** [comment]
Hello,

Datepicker is installed to the create project page and update project page. Now you will see a datepicker when you click on the date field. I have also corrected the date image css. We are using the icon as a ui element. Here is what you will see;

![screen shot 2015-05-13 at 13 54 23](https://cloud.githubusercontent.com/assets/2714346/7609861/cd9996fa-f977-11e4-8c78-1d5da69419d5.png)

You can skip months by clicking right and left arrows. You can also write the date directly but date should be in the yyyy-mm-dd pattern. System will correct it anyway.
