### ISSUE TITLE
Company page improvement

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#259]
Currently, in order to locate the company on a map, you can either enter the coordinates (lat and long), or point on the map the company location. People rarely know the lat and long of a company, and even if they have the adress it is sometimes difficult to locate the company directly on a map. Could the “address” info be used to locate automatically the company on the map?

**Comment by corner82** [comment]
There is an available service to get coordinates from adress info from google services, but I'm afraid after 2500 requests per daily it is paid service,  so can be implemented but may cause some payment if the program used intensively. Already Okan has prepared a structure to locate country of company automatically  from lat, long point information, so it is our choivce to implemet that  feature...

**Comment by emilyvuylsteke** [comment]
For info, if usefull: this issue is related to the issue number 98. Issue 98 is now closed.

**Comment by emilyvuylsteke** [comment]
Discussion on the subject have been made in subject 259. It is planned to implement the link "address-location on map" for version 1.1.
