### ISSUE TITLE
KPI should not be rounded to integer

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#260]
Now the KPI is rounded to integer (e.g. 0.4 --> 0 and 0.6 --> 1 or 1.4--> 1). This should not be the case. Proposal: the KPI should include 2 decimals. If the value is below 0.1 the value should be presented in scientific notation (e.g. 1.00 E-04, analog Excel)

**Comment by tcgumus** [comment]
As i remember we have fixed that issue. Can you share the page you have facing with this problem. Thank you

**Comment by catherine-moser** [comment]
![image](https://cloud.githubusercontent.com/assets/11196956/7351180/09c0dc4a-ed04-11e4-94b9-f3ea24053baa.png)

![image](https://cloud.githubusercontent.com/assets/11196956/7351199/21b81480-ed04-11e4-8372-d5ed53d2d67b.png)

**Comment by catherine-moser** [comment]
i will go home now. i'll comment on the other issues tomorrow :-)

**Comment by tcgumus** [comment]
Can you check it again. Please update the allocation and test if KPI value is rounded or not. 

Thanks

![screen shot 2015-05-13 at 13 11 47](https://cloud.githubusercontent.com/assets/2714346/7609291/daa6d016-f971-11e4-8bee-6872c74f6765.png)
