### ISSUE TITLE
CP scoping Graph: no data is displayed

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#261]
why? the numbers are not huge...
typo: * You wont be able to see every range on the graph, if one of them IS VERY BIG.
![image](https://cloud.githubusercontent.com/assets/11196956/7344658/df3a2c5a-eccd-11e4-85c3-d9dd3eeeb5ee.png)

**Comment by tcgumus** [comment]
hello. it is just a side info. you cant see anything in th graph since you dont have any rabge for ep values.

**Comment by catherine-moser** [comment]
Found out why: the accouracy rate was 100% --> Graph is just a point, not a bar. --> not visible
I changed accuracy rate to 70% then it worked.$
![image](https://cloud.githubusercontent.com/assets/11196956/7344731/7c564406-ecce-11e4-8f94-75604bb35367.png)

**Comment by tcgumus** [comment]
*range
i mean 51-51-51 it should be like 51-60-40 as an example

**Comment by catherine-moser** [comment]
i understand. Ep probably always has a range, but amount and cost can be measured --> very good data --> accuracy rate 100%.
But then nothing is visible on the graph. this should be changed

Data:
![image](https://cloud.githubusercontent.com/assets/11196956/7344766/ffe91a96-ecce-11e4-81f7-2066bc44cfe0.png)
Graph
![image](https://cloud.githubusercontent.com/assets/11196956/7344760/eff56162-ecce-11e4-9a45-3f1403334b1e.png)

**Comment by tcgumus** [comment]
minimum width and height added.
you can now see every process on graph even if they are too little
processes with 100% correction is now can be seen in the graph (bug fix)

![screen shot 2015-09-01 at 15 36 05](https://cloud.githubusercontent.com/assets/2714346/9604275/3c8234d4-50bf-11e5-9ab5-b7f03e1a57fd.png)
![screen shot 2015-09-01 at 15 31 45](https://cloud.githubusercontent.com/assets/2714346/9604276/3c843234-50bf-11e5-90b6-6c2ecbe7c65e.png)

**Comment by catherine-moser** [comment]
yup, works, thanks a lot!

**Comment by catherine-moser** [comment]
I would change the warning above the graph but I don't now how the graph is scaled exactely.
are big processes not displayed or are they displayed but then you can't see the small ones?
I would say something like: Not all processes will be visible if ...
![image](https://cloud.githubusercontent.com/assets/11196956/9604895/7c4beb78-50ba-11e5-9e31-235b000d328e.png)

**Comment by catherine-moser** [comment]
Hi Tuna
Just talking to Dirk and we agree that the line in the graph "100% = Benchmark" is very important for us. If it helps, you can limit the y-axis to 300% or 500% depending of the readabilty of the graph.

**Comment by catherine-moser** [comment]
Reminder to myself: check pop ups in the graphs.

**Comment by tcgumus** [comment]
i think you wrote this in a wrong issue. there is no benchmark in this graph

**Comment by catherine-moser** [comment]
ups you're right. sorry!

**Comment by tcgumus** [comment]
You are now seeing every process rather they are big or small. 
So i think we don't need this alert any more. Can we close the issue now?

**Comment by catherine-moser** [comment]
ok, delete the allert then i will close the issue.
it would be nice if the user would be able to scale the graph. is that complicated to implement?

**Comment by tcgumus** [comment]
i have deleted the unnecessary field. I will look for a way to scale the graphs. You can close the issue for now.

**Comment by catherine-moser** [comment]
ok I will close the issue and make a new one for the scaling with low priority (otherwise I will forget).
