### ISSUE TITLE
Navigate in projects, related to #134

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#264]
Related to #134

I find the navigation in the company pages very intuitive. Unfortunately the navigation in the project pages is not as intuitive. I propose to use a similar navigation in "projects" as in "companies". to be more specific:
- on the "My projects" page you can actually ENTER the project (red marks)
- by the way: what should be displayed in the box above the projects (blue marks)?
![image](https://cloud.githubusercontent.com/assets/11196956/7346878/fa44f498-ece2-11e4-9543-4bf31c9861fa.png)

- add "open project" button on the project page
![image](https://cloud.githubusercontent.com/assets/11196956/7346919/5bed00e6-ece3-11e4-87ec-6f32368e09fa.png)

- then you get to this page
![image](https://cloud.githubusercontent.com/assets/11196956/7346933/8f2672e4-ece3-11e4-9220-d4a7c41ed5ae.png)

- This button is no longer needed!
![image](https://cloud.githubusercontent.com/assets/11196956/7346947/b6098964-ece3-11e4-98c9-bbd9c49cd3cd.png)

**Comment by catherine-moser** [comment]
why are there 2 buttons for the Cost-Benefit-Analiysis?
![image](https://cloud.githubusercontent.com/assets/11196956/7347047/c8995e0a-ece4-11e4-9afc-4a2287d3059d.png)

if I click on the upper button i have to chose the project again even if i'm already working in the project.
![image](https://cloud.githubusercontent.com/assets/11196956/7347064/fb999b30-ece4-11e4-9705-9e5e0f9ea6f5.png)

In my opinion this upper button is not necessary.

**Comment by tcgumus** [comment]
Empty field was working for showing projects on map but we are using dump data to test it so sometimes it displays blank but it is working. I will just check the database and it will be fixed.

I can insert "open this project" button in the project pages but i think we will also need open new project button for the further requirements. It will help you and help us by making tool more flexible. 

Cost benefit module was in the cp scoping pages first then we have added IS parts as well and it became a global tool working with both cp and is. Thats why i needed to add the link to upper heading since it can be for users to access cba pages. For example if you are working of is scoping project you can easily access the cba pages also. Me and Ozgur thought that it will be better but of course we can delete or change it by talking on a hangout meeting :+1:

**Comment by catherine-moser** [comment]
i need to think about that. will get back to you tomorrow.

**Comment by catherine-moser** [comment]
i think the "open this project" button would definitely help.
https://cloud.githubusercontent.com/assets/11196956/7346919/5bed00e6-ece3-11e4-87ec-6f32368e09fa.png

i still don't understand why we need this button https://cloud.githubusercontent.com/assets/11196956/7346947/b6098964-ece3-11e4-98c9-bbd9c49cd3cd.png
, as we can open a NEW project here (create project) https://cloud.githubusercontent.com/assets/11196956/7346878/fa44f498-ece2-11e4-9543-4bf31c9861fa.png
but if you think we should keep it, we keep it! :+1: 

For the CBA: i'm not familiar with the IS module, therefore I can't say if the button in the heading is needed. for CP it is not needed. i think before we change it, we should ask Guillaume as he probably knows best about the requirements for working in IS. i will also ask Dirk about that.

**Comment by tcgumus** [comment]
The problem caused the map field to be blank has been fixed. Now you can see the map in the box. I think we should talk about the other part face-to-face :+1:

**Comment by tcgumus** [comment]
Open project button next to the projects list has been added. You can also close or update a project with newly added buttons. 
![screen shot 2015-06-09 at 13 49 06](https://cloud.githubusercontent.com/assets/2714346/8057053/550ed15e-0eae-11e5-9b10-c30fbb7b189a.png)

**Comment by catherine-moser** [comment]
super, thanks.
one additional thought: we should always use the same expression for the same "actions".
here these expressions
![image](https://cloud.githubusercontent.com/assets/11196956/8081328/2b44efb8-0f74-11e5-8da6-deb4308ff803.png)
and these expressions
![image](https://cloud.githubusercontent.com/assets/11196956/8081354/54c6dbc6-0f74-11e5-8bbd-898c222c1409.png)
lead to the same pages. i suggest to use these expressions
Edit Company Data
Edit Company Profile

**Comment by catherine-moser** [comment]
same here:
![image](https://cloud.githubusercontent.com/assets/11196956/8081465/52701382-0f75-11e5-8e3e-6172ab7205cb.png)
![image](https://cloud.githubusercontent.com/assets/11196956/8081778/0bfa9852-0f78-11e5-83dc-908b5fc31f65.png)

- use
Edit Project Info (top line)
Open Project (bottom line)
- if you click open project you should be directed to analysis

**Comment by catherine-moser** [comment]
also use the same expressions in the page itself
![image](https://cloud.githubusercontent.com/assets/11196956/8102194/613b4b4e-101e-11e5-8879-1cbdfa75d065.png)

**Comment by tcgumus** [comment]
Now we are using same text in every related page. Can you check it again?

**Comment by catherine-moser** [comment]
not yet changed everywhere :-)
my preference: use the words "edit", "cancel", "save"
also it would be nice if the colors would be the same everywhere. (ok for cancel, not for save)

profile: do we need both?
![image](https://cloud.githubusercontent.com/assets/11196956/9631757/5ce5d40a-5183-11e5-88f8-9089eea1576a.png)

![image](https://cloud.githubusercontent.com/assets/11196956/9631773/7d40298a-5183-11e5-8fe6-b465b5be0347.png)

company
![image](https://cloud.githubusercontent.com/assets/11196956/9631793/931f849e-5183-11e5-997d-ebb5ddf50c8e.png)

project
![image](https://cloud.githubusercontent.com/assets/11196956/9631801/a90c51b0-5183-11e5-90b6-ed50ad6da21d.png)

**Comment by tcgumus** [comment]
in the buttons i will use save right?

is there any other change you want

**Comment by catherine-moser** [comment]
yes use save.
can we make a quick hangout? i do not know how to explain in wrinting my other wish :-)

**Comment by tcgumus** [comment]
can you call me i can't call you

**Comment by catherine-moser** [comment]
solution as discussed:
user clicks on project name --> he gets to project page, header stays in project
user clicks OPEN project --> he gets to project page, header changes to analysis and shows CP, IS, CBA and so on.

**Comment by tcgumus** [comment]
converted "update" to "save".
now when you open a project you will see the analysis bar. When you close the project you will see the projects bar. 
Update profile button can be stay in the profile page. 
can we close the issue now :)

**Comment by catherine-moser** [comment]
Still think the (two :-) ) "update profile" button should be changed as well to "edit profile" button. then we use the same words everywhere.
save button in project is green while everywhere else it is gray.
sorry, can't close the issue yet :-)

**Comment by catherine-moser** [comment]
btw: I think the solution with the change to the analysis bar works great. thanks a lot!

**Comment by tcgumus** [comment]
Update profile changed to Edit profile
Update project button is gray now.

**Comment by catherine-moser** [comment]
perfect. now i can clos the issue :-)
