### ISSUE TITLE
“IS Manual (New company/Flow grid)” testing 

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#274]
I did the test with "Geneva test 2"

I select "wood" as a flow, then I click on “Begin Manual IS Process” and it give me a IS potential in aluminium and Arsenic (see print screen) . Is this normal? In my understanding, if a selected only “wood” flow, it means I am only interested in wood IS potentials. 
![image](https://cloud.githubusercontent.com/assets/10558805/7455196/4eda4304-f27a-11e4-9644-580ed799aec3.png)

Then, I try to click on the “Get specific flow info” and it does not show anything in the next panel. The only thing is that the name of the panel changes (see previous print screen – name: Aluminium). Therefore, when I click on “Add potential IS”, it does not work because I cannot see or select anything in the “aluminium” panel ( error message "Please select one row from all tables"). 

Please let me know if I am misunderstanding anything.

Thanks in advance!

**Comment by corner82** [comment]
Dear Emily,
here is my screen shot, so I can test issue, for testing purposes, please select 'test project for development'

![silinecek2](https://cloud.githubusercontent.com/assets/5053878/7455836/2f3c5934-f288-11e4-93a9-7833f1621738.png)

**Comment by emilyvuylsteke** [comment]
I am sorry I don't understand. Are you asking that I use another project for testing? Where do I have to select "test project for development"?

**Comment by corner82** [comment]
Because your selection does not match any more company on your specific project, please refer my settings cause we are testing with limited data, thanks...

**Comment by corner82** [comment]
Hi Emily ,
I checked database query again, query was right but 'IS sceanrio type' dropdown values made a trick in this situation too, so I changed rest service query wizard according to drop down values again
 screen shot below,

![silinecek2](https://cloud.githubusercontent.com/assets/5053878/7459775/f96d5e38-f2a6-11e4-89cc-fdf0c02e2b30.png)

Thanks for the valuable effort for this issue, we found a tricky buggy drop down value by your help, thanks anyway...

**Comment by emilyvuylsteke** [comment]
Still, when I select "wood" as a flow, it gives me IS potentials with Aluminium. Is this normal?

**Comment by emilyvuylsteke** [comment]
But when I click on "get specific flow", this step works fine. Still the first part of this issue is not solved, is it?

**Comment by corner82** [comment]
when you select wood and company, company related all flows are being displayed so yes this code part works like that, it is normal...

**Comment by emilyvuylsteke** [comment]
As discussed and as you suggested, we can remove the left panel of flows on this page, because it is not used in the quest anyway. Thanks in advance

**Comment by emilyvuylsteke** [comment]
I will open a new issue for this purpose
