### ISSUE TITLE
Delete the "IS manual" and the "IS automated" page and rename the "IS Manual (New company/Flow grid)" and the "IS automated (New company/Flow grid)" 

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#277]
Can we delete the "IS manual" and the "IS automated" old pages and rename the"IS Manual (New company/Flow grid)" by "IS manual" and the "IS automated (New company/Flow grid)" by "IS automated". Thanks in advance!

**Comment by corner82** [comment]
İssue can be tested, label changed 'waiting for testing'...

**Comment by emilyvuylsteke** [comment]
Thanks!
