### ISSUE TITLE
Add steps in the title of the panel for IS scoping pages

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#280]
As titles of the different panels, can you add:

For the IS automated page:
- Step 1: Flows
- Step 2: Company flow set
- Step 3: Dynamic table with IS potentials
- Step 4: IS potentials

For the IS manual page:
- Step 1: Company flow sets
- Step 2: Select flow from selected company  --> this title becomes "Select flow from - name of selected company - " once the use has selected a company . 
- Step 3:  Specific flow --> this title changes into the name of the selected flow once the user has selected a flow (same as it it now)

Thank you for this!

**Comment by corner82** [comment]
modifications done, label changed

**Comment by emilyvuylsteke** [comment]
Thank you for the changes! This helps to understand the structure of the tool. 

After discussion, we realized it would be even better to explain the action that is been taken in these steps. We are sorry to ask something different now, I should’ve realized before. I will therefore write down a new proposition for the steps titles. Please tell me what you think of those titles.

For the IS automated page:

Step 1: Select flow(s)
Step 2: Select a company and calculate IS potentials
Step 3: Select IS potentials from table 
Step 4: Save IS potential(s)

For the IS manual page:

Step 1: Select a company and calculate IS potentials 
Step 2: Select flow of selected company --> this title becomes "Step 2: Select flow of - name of selected company - " once the use has selected a company. This was already implemented, but the “Step 2” is missing for the titles when it changes. 
Step 3: Select the collaborative company --> this title does not changes into the name of the selected flow once the user has selected a flow. 

What do you think? I think it would be extremely useful for the users. 

Also, can you make the police bigger or bold for better visibility of the structure?

**Comment by corner82** [comment]
I will consider this issue in the workflow on the new version, thanks

**Comment by gmassard** [comment]
Hi,
I think we can start working on this issue now.

**Comment by corner82** [comment]
issue closed...
