### ISSUE TITLE
Zoom function for map showing scenarios

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#281]
For both the "IS scenario" pages and the IS scoping pages, when we click on "see on map" to see the scenario on a map, there are 2 things we would like to change if possible:

- Can the zoom level of the map be define to show all the companies integrated in the scenario? For the moment it usually shows only one, then you need to un-zoom to see both of the companies involved in the scenario. 
- Can we make the zoom function for the map only controlled by the "+" and "-" buttons on the map and not by the scrolling of the mouse? In this way, the scrolling only serves the function to go up and down on the page.

**Comment by corner82** [comment]
Both topics has been implemented on Is map pages, label changing 'waiting for testing'

**Comment by corner82** [comment]
Why did you change label, did you test it? I'm using these label things to do things in order, not working for you?

**Comment by emilyvuylsteke** [comment]
Yes I tested and commented.. I'm sorry it seems like my comment has not been saved or I made a mistake. My comment was the following:
Thank this works fine for the IS scoping page. But it has not been changed on the "IS scenario" pages. Thanks in advance.

**Comment by emilyvuylsteke** [comment]
I'm sorry I will not change the labels anymore. I was changing them because it made it easy for me to still see what I needed to check on the list. When a "waiting for testing" label was on, that meant I had to check again. But maybe it is easier not to change too much the labels.

**Comment by corner82** [comment]
same feature has been added to 'IS scenario' pages too...

**Comment by emilyvuylsteke** [comment]
As I said before, this issue is resolved perfectly for IS scoping pages.
Concerning the IS Scenarios pasge:
- Now the zooming function for the map is working with the button + and - . So this is ok!
- But the initial zoom level still shows only one of the company involved in the scenarios. We want to see both companies, same as in the IS scoping pages. Can you resolve this detail? Thanks in advance Zeynel!

**Comment by corner82** [comment]
Zoom level on IS scenario pages has been updated, issue closed
