### ISSUE TITLE
Status column in the "IS scenario" table on "IS scenario" page

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#282]
On both IS scenario pages, can we add a column in the main "IS scenario" table displaying the status of the scenarios that was indicated when the scenario was saved?

**Comment by corner82** [comment]
IS scenario pages main data grid modified to show 'status' column, issue can be tested, label changed 'waiting for testing'...

**Comment by emilyvuylsteke** [comment]
I can see the status column in the consultant page but not in the supervisors page

![screen shot 2015-05-05 at 15 34 28](https://cloud.githubusercontent.com/assets/10558805/7473538/417a3fc6-f33c-11e4-8c19-b981bbdf321a.png)

**Comment by corner82** [comment]
Ican see on both pages, please refresh web page, somteimes web browser cache can be tricky

**Comment by emilyvuylsteke** [comment]
I'm sorry it does not work for me on the supervisor page. I just tested again.. (cfr print screen with date and time)
![screen shot 2015-05-05 at 15 43 23](https://cloud.githubusercontent.com/assets/10558805/7473754/a2c55f3a-f33d-11e4-9787-71282fa67173.png)

**Comment by corner82** [comment]
here is my screen shot,

![silinecek3](https://cloud.githubusercontent.com/assets/5053878/7473884/d0b2af0c-f346-11e4-8b35-d53b745f26d5.png)

**Comment by emilyvuylsteke** [comment]
But is this for the consultant or the supervisor page?

**Comment by corner82** [comment]
Please check the link, is not the same link with your screen?, I see they are the same links ...

**Comment by emilyvuylsteke** [comment]
It shows the same for me in the consultant page.. but when I click on "IS scenario (supervisors)" it shows the printscreen I shared above..  
What link are we talking about?

**Comment by corner82** [comment]
![silinecek3](https://cloud.githubusercontent.com/assets/5053878/7474045/a933f7fa-f347-11e4-8958-ada5bb85d207.png)

**Comment by emilyvuylsteke** [comment]
The links are the same (88.249.18.205:8090/ecoman/isscenarios). I do not know how it it possible, but you can also see my screenshot with time etc.. this is a screenshot of the supervisors page.

**Comment by corner82** [comment]
Maybe your web browser cache can cause this,....We will look at it together...

**Comment by emilyvuylsteke** [comment]
I have cleared my browser cache ( and indeed it solved some problem, eg issue 278) but with issue it does not make any change. I still don't see the "status" column in the "IS scenarios (supervisors)" page.

**Comment by corner82** [comment]
I will send an video screen proving issue is complete, issue closed
