### ISSUE TITLE
Dataset management button from IS scoping pages

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#283]
Both in the "IS manual" and the "IS automated" page, we find the " Dataset management" button that you access by click on the "+" button for a flow or company, in the "dynamic table for IS potentials". For the moment, when you click on the "dataset management" button,  it leads to data management page, then when you go back to the IS scoping page, it has to re-process the IS potential from the beggining. Would it be possible to open the dataset management page in a new tab? In this way, we will not lose the process of the IS scoping page.

**Comment by corner82** [comment]
already managed in #279 , you may test it, label changed

**Comment by emilyvuylsteke** [comment]
Thank you for acting so fast :)! But I just tested it and it didn't work for me. Neither on "IS Manual" nor in "IS automated" page. What we meant is that the dataset management should open a new internet page, leaving available and displayed the IS scoping pages.

**Comment by corner82** [comment]
Server code has just been updated, would you test again please...

**Comment by emilyvuylsteke** [comment]
I just tested for both manual and automated. The used page changes to data management. No opening of new page.

**Comment by corner82** [comment]
Please don't change label again, I just tested again and it is working for me , we can test it together on next hangout...

**Comment by emilyvuylsteke** [comment]
no I won't change label and I will be testing tomorrow if this is fine. It should be implemented by tomorrow right? Thank you anyway for you rapid response. Hope all this work is not lost..

**Comment by corner82** [comment]
it is already implemented, but you can see some how, nevermind I will share screen then, maybe we can understand the problem...

**Comment by emilyvuylsteke** [comment]
This is still not working. The dataset management does not open in a new independent page. I am sending a video for this matter to show what happens.

**Comment by emilyvuylsteke** [comment]
It does not work neither for manual IS nor for automated IS

**Comment by corner82** [comment]
Ok I think I misunderstood the requirement, I took my notes for IS scenario pages data set management links, and I have changed them, so I will make a quick refinement On other pages too, I will inform you

**Comment by corner82** [comment]
Hi Emily,
I just looked at IS pages, and I could not find the link to change exactly, I'm sending you the screen shot of what has been changed, would you please add a screen shot for to realize what has to changed ,
I have ckhanged links on Is scenario page, here is the screen shot below,

![silinecekler](https://cloud.githubusercontent.com/assets/5053878/7514308/04fb78aa-f4c5-11e4-9a2c-f169feed86ae.png)

**Comment by corner82** [comment]
I added new links to related pages too, I'm sending Emily an mp4 video sharing my screen proving that issue fullfilled, my test scenes will be on that video, so I'm closing issue
