### ISSUE TITLE
For further version: Rescale the "dynamic table with IS potentials" panels

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#284]
If possible, could you rescale the "dynamic table with IS potentials" panels in both IS scoping pages (Manual and automated). There are quite small and when you click on the "+" button to have more details , it is not easy to visualise those details. Here are some print screens to give an idea:

![screen shot 2015-05-05 at 11 40 10](https://cloud.githubusercontent.com/assets/10558805/7470360/b0db4eca-f31c-11e4-9916-dcc60dc79edb.png)

![screen shot 2015-05-05 at 11 37 52](https://cloud.githubusercontent.com/assets/10558805/7470361/b3c11fca-f31c-11e4-8460-bd67d30a9392.png)

**Comment by corner82** [comment]
I think that is not issue for this verison, I will make it version for 1.2 if possible, that is not an issue interrupting the user from using IS pages

**Comment by emilyvuylsteke** [comment]
Ok we can deal with this later

**Comment by gmassard** [comment]
Hi,
I think we should start working on this issue now.
Guillaume

**Comment by corner82** [comment]
when expand the row the right side panel closes and when you collapse the row panel sizes change and the right side panel opens again....

**Comment by corner82** [comment]
Dropbox IS-GIS document IS-11
Dropbox IS-GIS document IS-13
