### ISSUE TITLE
Map in the "automated IS" page

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#285]
Following our discussion on hangout concerning this map, I discussed again with Guillaume. We suggest the following for the moment:

Can we delete the map that is currently embedded in the "automated IS" page? The map will display only when we click on the "see on map" button to visualise the scenario, same as on the "manual IS" page.

Guillaume was suggesting to maybe add a button to access GIS info of the project directly from this page. But maybe we can postpone this for the next version.

**Comment by corner82** [comment]
Modifications done, before testing please (ctrl+f5) on web browser link, cache will be deleted, label changed...

**Comment by emilyvuylsteke** [comment]
Ok this has been tested. I will close issue.

**Comment by emilyvuylsteke** [comment]
I will nevertheless open a new issue for the following : "Guillaume was suggesting to maybe add a button to access GIS info of the project directly from this page. But maybe we can postpone this for the next version." But as said before, we can leave this for further version.
