### ISSUE TITLE
when selecting a group in the flows, the subgroups integrated in this group should be selected

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#286]
As discussed on hangout, when selecting the group, it should automatically integrate all the subgroups. When shouldn't need to open the group and select all of them manually. Both in IS manual and IS automated pages. Thanks in advance!

**Comment by corner82** [comment]
modifications done, label changed....

**Comment by emilyvuylsteke** [comment]
This works fine!! Thanks!
