### ISSUE TITLE
When there is no IS potential with the selected elements, send a message explaining

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#287]
When it not possible to suggest a IS potential with the selected elements, can we send a message to the user mentioning "there is no IS potential with the selected elements" or something like that.. Could that be easily done? It could be either a popout message, or integrated in one of the panel.. Something visible enough. What do you think?

Thanks in advance!

**Comment by corner82** [comment]
YEs a pop can be diplayed on screen with corresponding message, we should determine where and when to display a popup , and then workout can be planned....

**Comment by emilyvuylsteke** [comment]
on "manual IS":
at step 2, when clicking on "Get specific flow info", if there is no IS potentials and nothing can display on the next panel, a popout message should display at that moment, mentioning the following: " There is no IS potential for the selected flow category. Please select another flow category". 

on "automated IS":
At step 2, when clicking on "calculate IS potentials", if there is no IS potentials and nothing can display on the next panel, a popout message should display at that moment, mentioning the following: " There is no IS potential for the selected selected company in this category of flow. Please select another flow category and/or company".

**Comment by gmassard** [comment]
Hi Zeynel
Where do you stand with this issue?

**Comment by corner82** [comment]
issue closed, Is dokumantation updated, new IS scenario added, please check out

**Comment by gmassard** [comment]
Hi Zeynel,
Sorry but I have to reopen this issue as well. On automated IS, there is no message displayed when no IS potentials exist..
On manual IS, the message only mentionned "test". See image below.
Can you please fix it.

![287_screenshoot1](https://cloud.githubusercontent.com/assets/9587966/9161971/0cb1b8e2-3f44-11e5-8985-e6f2cea30b5e.png)

**Comment by corner82** [comment]
dropbox IS-GIS document IS-09
