### ISSUE TITLE
Line between companies on the IS scenario maps of the "IS scenarios" pages

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#289]
This issue was previously mentioned in the issue number 236. I closed this issue to open an issue specifically on this matter:

On the "IS scenarios" pages (both consultant page and supervisor page), on the map showing the scenarios, there is not line between the companies. We would like a line between the companies, like there is in the map displaying on the IS scoping pages. Here is a printscreen of what appears. Thanks in advance! 
![screen shot 2015-05-07 at 11 36 51](https://cloud.githubusercontent.com/assets/10558805/7512503/c3af34fc-f4ad-11e4-91a0-e2e0f5223c04.png)

**Comment by corner82** [comment]
this issue company specific, cause on many companies tthere is no problem,I will consider this issue in the workflow on the new version, thanks

**Comment by corner82** [comment]
You may test issue now, a new trigger added to database, below the screen shot, labet changed 'waiting for testing' , tester may close issue

![silinecekler](https://cloud.githubusercontent.com/assets/5053878/7533477/84b2f392-f57a-11e4-9c56-fa6af648b565.png)

**Comment by emilyvuylsteke** [comment]
This works fine now! Thank you! I will close issue
