### ISSUE TITLE
Map in IS scoping: "close map" button be on the map itself

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#290]
This is an issue for further version, but we think it would be more user friendly to have the "close map" button on the map and not above the first panel.

**Comment by corner82** [comment]
I will consider this issue in the workflow on the new version, thanks

**Comment by gmassard** [comment]
I think we can start to work on this one no?

**Comment by gmassard** [comment]
Yes, Zeynel will start working on it

**Comment by corner82** [comment]
on map panels on the right top corner, there is a close button...thanks...

**Comment by gmassard** [comment]
Yes, I see the button. Please write "Close map" aside from the button. The user may not find it otherwise.

**Comment by corner82** [comment]
Hi this is panel element and panel element can only have custom tools (not link button), 
this issue documented in dropbox IS-GIS document IS-12, closing issue
