### ISSUE TITLE
error message "please select a subflow from flow tree" on "automated IS" tool

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#291]
There is a small bug on the "automated IS" tool.

When I select flow category "energy" and then a specific company, then click on "calculate IS potentials", an error message tells me to "Please select a sub flow from flow tree". The sub flow are actually selected but it's just that the project itself does not have energy flow data. This is the reason it does not work I guess, but the error message is false. It should say " There is no IS potentials for the selected company with this flow category. Please select another company and/or flow category". No?

Here is a printscreen 
![screen shot 2015-05-11 at 09 54 14](https://cloud.githubusercontent.com/assets/10558805/7560672/9e45e614-f7c5-11e4-86fd-315aaf31c456.png)

**Comment by corner82** [comment]
Alert message has been changed as you suggested, I tested and seemed resolved to me, you may test and close issue, label changed

**Comment by gmassard** [comment]
Now it seems that there is no message appearing when you perform an IS detecting with flow categories that do not exist in the dataset.
No results are shown.

Was it the aim of your improvement Zeynel?

Best

Guillaume

**Comment by gmassard** [comment]
Ok, message error fixed.
But when no IS is detected please show a message on the datagrid (STEP 3) saying:
"No symbiosis detected"

**Comment by corner82** [comment]
issue closed, Id documents page has been revised due to issue requirements
