### ISSUE TITLE
error message "Please select company" on "automated IS" page

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#292]
At step 2, when I select a company a first time, then I change my mind and select another one and de-select the first one, then click on "calculate IS potentials", it sends an error message telling me that I should "select a company" (see printscreen). A company is actually selected so the error message is false. It's as if it did not recognised the selected item..

![screen shot 2015-05-11 at 09 48 57](https://cloud.githubusercontent.com/assets/10558805/7560790/ab61e0d6-f7c6-11e4-88e1-2d5467ce88b0.png)

**Comment by corner82** [comment]
Done modifications to 'idfield' property of datagrid,  on my testing  it seems resolved, please test issue, you may close issue if resolved, label changed....

**Comment by gmassard** [comment]
Yes, i seems solve to me!
Thank you
