### ISSUE TITLE
New flow chrome storage bug

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#294]

**Comment by catherine-moser** [comment]
![image](https://cloud.githubusercontent.com/assets/11196956/8698676/529469e8-2b00-11e5-8593-bf822b326d7c.png)

**Comment by catherine-moser** [comment]
on the other hand, if an error occurs when adding a new flow the data that was already entered should be stored.

**Comment by tcgumus** [comment]
now new flow form is storing data when it fails. so you can just correct the error giving part and continue. :+1:

**Comment by catherine-moser** [comment]
yes that works. 
BUT:
I add all the data for Flow 1 and save it.
then I click add new flow
--> the data from Flow 1 is stored. this is not desirable. if I click new flow, the form should be empty. otherwise mistakes can happen.

**Comment by tcgumus** [comment]
now it doesn't show stored data after a successful form submission.

**Comment by catherine-moser** [comment]
yes, work perfectly. thanks!
