### ISSUE TITLE
IS manual: change in step 3 

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#296]
Hi,
When I user is trying to manually selecting a flow (step 2: select flow from selected company), currently he only see appearing on step 3 data from other companies having the same flow name.
The purpose of the manual selection is to allow to link a flow with another one that has a different name.

Can you change the code so that, when clinking on "Get specific flow info" in step 2, ALL input and output flows from other companies in the project are display. Then the user can choose any flow, even if flow name is different.
Ok?

![geneva_test_2](https://cloud.githubusercontent.com/assets/9587966/7704320/f33492be-fe3d-11e4-82cc-27686c323099.png)

**Comment by gmassard** [comment]
Lower right table, will display all company name and flow info, except the one selected in lower left table.
Then user can choose two flows that as a different name and link them together. Then save it as a potential.

**Comment by corner82** [comment]
Dropbox IS-GIS document IS-14
