### ISSUE TITLE
IS Scenario (consultant and supervisor): scenarios from other project appear in the list

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#297]
Hi Zeynel,

I created a new project (Geneva_FTI_Case1) to run a full test. After manual and automated IS, I went on the IS scenario(consultant) and IS scenario (supervisors) pages to see the saved IS potential.
I created only 3 scenarios for this project (the 3 first on the image). However, the list display scenario that are related to other projects.
Can you fix it urgently for demo tomorrow.

Thank you!

![geneva_test_3](https://cloud.githubusercontent.com/assets/9587966/7704480/f193467a-fe3e-11e4-8d52-226f94f1c5bd.png)

**Comment by corner82** [comment]
IS scenarios are totally different type projects, so other projects we open when we set are cp projects, so on Is scenario pages the projected related to the consultant appear.
On consultant IS scenario page IS scenarios are already being displayed according to consultant id and consultant related ,
On supervisors is scenarios page all IS scenarios were being displayed, but it was changed as consultant id related as the other page...

**Comment by gmassard** [comment]
Hi Zeynel,
The IS scenario page should display saved scenario not on a consultant base, but on a project base.
Then we should imagine to adapt the consultant and supervisor page in order to:
1. Have an IS scenario (consultant) page that display all scenarios related to the consultant
2. Have an Is scenario (project) page that display only the saved scenario from the current project.
Thank you! 
Guillaume

**Comment by corner82** [comment]
On consultant IS scenario pages, is scenarios are dispalyed by project id,
new ıs scenarios are being saved with opened project id,
for test purposes Guillaume and Emily can test ıs scenarios with project 'geneva test 3', thank you...

**Comment by corner82** [comment]
Dropbox IS-GIS document IS-01
