### ISSUE TITLE
GIS framework: start to enhance this functionality

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#298]
Hi Zeynel,

We can start working on the GIS framework now to make it fully operational.
1. When you are log to a specific project, and you click on the GIS button, the GIS framework should open directly on the project location.
2. When opening on the project location, the map can directly display "dots" on company location (only companies that are in the project, of course).
3. Question: how do I save and recall information that I draw on the map? I'm not sure how to do it. It is very usefull for user.

Thank you!

Guillaume

**Comment by gmassard** [comment]
Zeynel start working on point 1 and 2.
Zeynel and Guillaume start working on a new use case for the GIS framework, to describe all functionalities to implement.
Zeynel create a document and share it with me for contribution.

**Comment by corner82** [comment]
done according to dropbox IS-GIS document GIS-01 scenario...
