### ISSUE TITLE
GIS: harmonize all map related API

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#301]
Hi Zeynel,

Please contact Tuna to deal with this issue. In the tool, we have currently several types of maps, that are using different API, such as the map data from google imagery you are using in the IS scoping scenario page, and the leaflet from open street map that Tuna is using.

Please coordinate together to harmonize the API and make sure that you all use the same.

Guillaume

**Comment by gmassard** [comment]
Zeynel suggest to harmonize maps using google map to be able to use the location finder.
Tuna, do you agree to change from Leaflet to Google map?

**Comment by tcgumus** [comment]
We can use leaflet as a location finder as well so i suggest to not change anything if we arent able use our system in an iframe

**Comment by gmassard** [comment]
Ok! Then please compare all functionalities and free version capacities! Which is the best option?
We need to make a choice!

**Comment by tcgumus** [comment]
We can use google maps for the maps we will create in the portal but working maps has already implemented and they don't have any usage limit so i think they can stay

**Comment by tcgumus** [comment]
As you can see in the project pages i have moved the GIS map in to map field that implemented by Zeynel. So, as long as Zeynel or Okan create new GIS maps for other pages , i can implement them like the project page as well. Other than that i don't think i can implement the GIS to the other pages. 

Regards,
Tuna

![screen shot 2015-05-30 at 14 31 09](https://cloud.githubusercontent.com/assets/2714346/7897477/5e0a1346-06dd-11e5-8397-b8a33d4197c7.png)

**Comment by gmassard** [comment]
Than we will have Map Data on all pages, right? 
Ok! Sounds good to me!
