### ISSUE TITLE
Product amount can only be entered as integer

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#302]
should be changed, also eg. 0.5 should be possible

**Comment by tcgumus** [comment]
![screen shot 2015-09-03 at 09 11 46](https://cloud.githubusercontent.com/assets/2714346/9651640/f123b130-521b-11e5-8760-0a25fd68705e.png)
now you can enter values with precision

**Comment by catherine-moser** [comment]
thanks!
