### ISSUE TITLE
Open project: system should display the project information page

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#309]
Hi, When the user open a project, the system display the screen with the large picture of Ankara (I guess). Then the user does not know what to do...

Please change it so that the system display direcly the related project page. See image below.

![geneva_test_7](https://cloud.githubusercontent.com/assets/9587966/7721214/e8e5dcda-fed5-11e4-8890-bea553433862.png)

**Comment by tcgumus** [comment]
Open project button inside of the project pages has been inserted.
