### ISSUE TITLE
The order of the following button should be modified : "create company", "create project", "open project"

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#331]
The buttons in the title (presented in the printscreen) of the issue should be presented, from left to right, in the following order:
1. create company
2. create project
3. open project

![screen shot 2015-05-26 at 10 46 26](https://cloud.githubusercontent.com/assets/10558805/7808569/7b3770c2-0394-11e5-8a9a-edf8286504e8.png)

**Comment by tcgumus** [comment]
Since we have a new navbar/header i think this issue is outdated. Can we close it?
