### ISSUE TITLE
Consultant opening the project should be a possible "contact person" of the project

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#335]
When assigning the contact person of a project, the given possibilities for the moment are the users linked to the involved companies. There should be a possibility to choose the consultant that is opening the project as well.

**Comment by tcgumus** [comment]
solved. Now you can add yourself as a contact person of a project if you are creating one.

**Comment by catherine-moser** [comment]
when i was testing i could ONLY add myself. eventhough i added other consultants to the project,

**Comment by tcgumus** [comment]
you can add other if there is user in the added companies. If there is no user in the added companies you will only see yourself.

**Comment by tcgumus** [comment]
please test and close

**Comment by catherine-moser** [comment]
ok, thanks
