### ISSUE TITLE
IS scenario data should be recalculated every time consultants opens an IS scenario

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#336]
Current situation: when a scenario table is saved, the data it contains are freeze (compared to the data in the database). So if the user edit or add a data, in the dataset management, the scenario results will not be updated. This is a problem as scenario are then use in the cost-benefit analyses.

Situation we would like to implement: when user open a scenario, data of the scenario should be recalculated every time, based on the dataset management data. It will be everytime updated. This will allow user to work on (1) dataset management (2) IS Identification (3) Cost benefit analyses (4) Reporting by using always the same up-to-date data.

This will solve the data edition problem in both dataset management and IS potential. (also see next issue)

**Comment by corner82** [comment]
Database trigger has been placed, when company flow updated is poroject table will be changed

**Comment by gmassard** [comment]
Hi! I just tested the scenario recalculation improvement. The goal is not achieve. See in following picture: when a data is updated in database (34000 tons of "cuivre" changed to 24000 tons), the scenario calculation result is not change. The data is updated in the data display table at the bottom of the page, but not in the scenario display. 
Data need to be updated entirely. 

![336_screenshoot1](https://cloud.githubusercontent.com/assets/9587966/9132553/9efde3da-3cf4-11e5-90dd-d7ccd08aca7d.png)

**Comment by corner82** [comment]
ok I will check it out, thank you..

**Comment by corner82** [comment]
please try again...thanks

**Comment by gmassard** [comment]
Hi Zeynel,

I have check and it seems to work now! Emily and I are now starting a large scall test to check for last details.

Best.
