### ISSUE TITLE
IS manual and automated detection: replace edit data links with a link to dataset management (edit company flow)

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#338]
In IS manual and automated detection, in order to solve the database integrity problem, we need to remove the "edit" feature that we have implemented in the IS tables... (Edit anyway does not work now).

I suggest to replace it with a direct link the "edit page" of this specific flow, in the dataset management:
http://88.249.18.205:8090/ecoman/edit_flow/139/3/1

Then, when the data update is saved. Tuna will put a new button to get back to IS detection.

**Comment by corner82** [comment]
issue closed

**Comment by corner82** [comment]
Dropbox IS-GIS document IS-07
