### ISSUE TITLE
delete "get to know", "user profiles" etc

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#345]
the difference to the other texts which are links are not visible --> confusing for the user when he can click on some texts and not on others.
![image](https://cloud.githubusercontent.com/assets/11196956/8082081/d3621526-0f7a-11e5-9212-7135888ff7ed.png)
![image](https://cloud.githubusercontent.com/assets/11196956/8082082/da493ee6-0f7a-11e5-81c1-334e8541fd4f.png)
![image](https://cloud.githubusercontent.com/assets/11196956/8082093/e9576db8-0f7a-11e5-8bd4-ec2738d04404.png)

**Comment by tcgumus** [comment]
Deleted the header description fields.

**Comment by catherine-moser** [comment]
ok, thanks.
just a "nice to have": maybe we could move the text more to the right? e.g. begin under the active header? I think we already discussed this possibility once.
![image](https://cloud.githubusercontent.com/assets/11196956/8132273/daf21848-1120-11e5-89a1-9403c42cbb47.png)

![image](https://cloud.githubusercontent.com/assets/11196956/8132281/e8c717e8-1120-11e5-8f45-30c094e17fdb.png)

**Comment by tcgumus** [comment]
I have thought the same thing but in the analysis tab there lots of tools and it will be a big space to the left.

**Comment by catherine-moser** [comment]
maybe we could make a compromise and always start below "profiles".

**Comment by tcgumus** [comment]
solved.

**Comment by catherine-moser** [comment]
i think it looks good that way, thanks.
