### ISSUE TITLE
wrong redirection

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#347]
![image](https://cloud.githubusercontent.com/assets/11196956/8082434/9abb94b0-0f7d-11e5-9d04-2d980ab25389.png)

you should stay in Profiles (orange)

**Comment by catherine-moser** [comment]
dito
![image](https://cloud.githubusercontent.com/assets/11196956/8082464/db39d7ae-0f7d-11e5-84d1-566738fa74b2.png)

**Comment by tcgumus** [comment]
Navbar has been modified to work on login and register pages also. 
![screen shot 2015-06-12 at 16 15 54](https://cloud.githubusercontent.com/assets/2714346/8131968/54b745ac-111e-11e5-96c0-6500dd38e05d.png)

**Comment by catherine-moser** [comment]
perfect
