### ISSUE TITLE
Not all data that is entered in the user profile is displayed. why?

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#350]
only "Job title" is missing.
"Description" called "user info" --> use description throughout.
Company see #349
![image](https://cloud.githubusercontent.com/assets/11196956/8084119/8c6982e4-0f89-11e5-885f-0916520e583d.png)

![image](https://cloud.githubusercontent.com/assets/11196956/8084127/9e39379e-0f89-11e5-95de-f8010059950c.png)

**Comment by tcgumus** [comment]
I have also added the job title info to the user info table.

**Comment by catherine-moser** [comment]
ok, thanks
