### ISSUE TITLE
Bar Companies

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#352]
change order
![image](https://cloud.githubusercontent.com/assets/11196956/8084812/5223d8d8-0f8d-11e5-9c8e-d5e115565acd.png)

User: my companies / all companies / create company
Consultant: my companies / my project companies / all companies / create company

**Comment by catherine-moser** [comment]
related to #264
there are 3 places where navigation is placed. this is to much.
![image](https://cloud.githubusercontent.com/assets/11196956/8085410/457dacd2-0f90-11e5-98c6-bc906899019a.png)

Suggestion to reduce to 2 places: integrate add user to "edit company profile"
![image](https://cloud.githubusercontent.com/assets/11196956/8085509/d61fa506-0f90-11e5-92fa-a615a9466536.png)

**Comment by catherine-moser** [comment]
maybe we could also move the button to the side? (in all pages) what do you think?
![image](https://cloud.githubusercontent.com/assets/11196956/8085634/667bee70-0f91-11e5-90ef-0f0a535dc451.png)

**Comment by catherine-moser** [comment]
"My project companies" does not appear even thought i'm logged in as consultant.
![image](https://cloud.githubusercontent.com/assets/11196956/8085707/d1406268-0f91-11e5-842d-e9f36a977904.png)

**Comment by catherine-moser** [comment]
if i open the datasetmanagement of a company, automatically the analisis bar opens. i would be ok with that, but the problem is this sentence. The user thinks he can't do anything, but he CAN do something (CRUD data)
![image](https://cloud.githubusercontent.com/assets/11196956/8207231/2dfbeca2-1500-11e5-9b59-adb688daeb8d.png)

**Comment by tcgumus** [comment]
now in the dataset management "companies" bar is opening.
I have already updated the company pages, project pages and profiles

**Comment by catherine-moser** [comment]
thanks!
