### ISSUE TITLE
Bar Projects

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#355]
Projects do not appear in the same order as in profiles
![image](https://cloud.githubusercontent.com/assets/11196956/8101723/225d98cc-101a-11e5-863a-57834ce4d4f4.png)
![image](https://cloud.githubusercontent.com/assets/11196956/8101732/36ca0cfa-101a-11e5-8362-b194c44067db.png)

**Comment by catherine-moser** [comment]
all projects:
no "edit" buttons for my project.
(in companies this feature exists and I like it)
![image](https://cloud.githubusercontent.com/assets/11196956/8101759/761c292e-101a-11e5-92ac-c1884f577097.png)
![image](https://cloud.githubusercontent.com/assets/11196956/8101774/8f6db776-101a-11e5-8848-ec674985b566.png)

**Comment by catherine-moser** [comment]
may be we could also move these buttons to the right.
see also #352 and #264 (for names)
![image](https://cloud.githubusercontent.com/assets/11196956/8102317/68351b9a-101f-11e5-9475-ead3348a2fe5.png)

**Comment by catherine-moser** [comment]
if you click "close project" you get to homepage 
![image](https://cloud.githubusercontent.com/assets/11196956/8102355/b865897e-101f-11e5-845a-ea044877f863.png)
I think you should go my projects

**Comment by catherine-moser** [comment]
Under my projects no projects are listed if i'm logged in as a user (even thought I'm contact person of a project).

**Comment by catherine-moser** [comment]
if i'm logged in as a user and click "create project" i'm directed to homepage. But error message should appear saying that i need to be a consultant to create a project.

**Comment by tcgumus** [comment]
Profile pages now orders projects based on their name.
Open project and edit project button has been added to “all project”
page.
Now you can see, edit and open projects if you are a contact person of
that project.
Closing a project now directs you to “my projects” page.
“Sorry, you need to be a consultant to create a new project.” error
message has been added.
“Sorry, you dont have permission to open this project..” error message
has been added.

**Comment by catherine-moser** [comment]
super! Thanks!
(Moving buttons will addressed in issues  #352 and #264)
