### ISSUE TITLE
Analysis bar

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#360]
if i open the datasetmanagement of a company, automatically the analisis bar opens. i would be ok with that, but the problem is this sentence. The user thinks he can't do anything, but he CAN do something (CRUD data). On the other hand, since the data is linked to a specific company, it would also make sense to stay in the companies bar.
![image](https://cloud.githubusercontent.com/assets/11196956/8207461/f1f8eb90-1501-11e5-9865-e9c7cd5c7ee2.png)

**Comment by catherine-moser** [comment]
- to make it similar like the profile bar, the "close project" button should be moved to the bar Projects
- The name of the project should be moved to the right, to distinguish it from the tools (see also #359)
![image](https://cloud.githubusercontent.com/assets/11196956/8208403/c78d28de-1507-11e5-98be-2671576870b7.png)

**Comment by tcgumus** [comment]
Project name and close project button have been moved to project bar.
Dataset pages now show company bar. Not analysis.

**Comment by catherine-moser** [comment]
thanks
