### ISSUE TITLE
Bar Project

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#361]
Move the buttons to the left (analog bar companies)
![image](https://cloud.githubusercontent.com/assets/11196956/8207534/744e98a6-1502-11e5-8ae2-a88f049267bd.png)

**Comment by catherine-moser** [comment]
would it be possible to open the project directly when i click on the name? then it would work like in the companies bar.

**Comment by catherine-moser** [comment]
after you create a project, you should be directed to My projects, not all project (in my opinion).

**Comment by tcgumus** [comment]
Projects page updated.
Users will now redirected to myprojects page after they created a new project.
We have talked about the “open project when a project page opened” problems.

**Comment by catherine-moser** [comment]
thanks!
