### ISSUE TITLE
Rights and privileges

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#362]
if I create a project,  i can add any company, regardless if i'm a consultant/user for that company. After, if I open the project, i can all the company data incl. dataset management. This is very problematic for confidentiality reason!
I see 2 possibilities to solve this:
1. you can only add companies for which you are user or consultant to a project.
2. you can add any company to a project, but you can only see the data for your companies.

what do you think?

**Comment by tcgumus** [comment]
The company list on the project creation page will be updated to the companies that you have permission on.

**Comment by tcgumus** [comment]
you can only add companies you have rights.
 Now “my companies” page will show every company that you have
permission to edit on.
“new project” page company selection field will only have companies
that you have rights. Not all of the companies in the system

**Comment by catherine-moser** [comment]
ok, thanks!
