### ISSUE TITLE
Error in English

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#367]
could you display this error message in Englisch please
![image](https://cloud.githubusercontent.com/assets/11196956/8402245/e34dad9c-1e39-11e5-9da9-50fcad384c12.png)

**Comment by catherine-moser** [comment]
also here
![image](https://cloud.githubusercontent.com/assets/11196956/8402270/36eb7a06-1e3a-11e5-89d1-2c7830e2e598.png)
and here
![image](https://cloud.githubusercontent.com/assets/11196956/8402291/9eab50b2-1e3a-11e5-88fb-5bcca5888da4.png)

**Comment by tcgumus** [comment]
fixed

![screen shot 2015-07-01 at 16 39 44](https://cloud.githubusercontent.com/assets/2714346/8457127/ddfccb70-200f-11e5-84d6-2233f6777e3b.png)

**Comment by tcgumus** [comment]
Mails are also fixed

**Comment by tcgumus** [comment]
fixed again

**Comment by catherine-moser** [comment]
tested! thanks.
