### ISSUE TITLE
My first user cannot login to application

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#375]
My very first user can not login to system anymore, it can be an earlier bug or newly cretaed code bug , anyways I have to figure out why ?

**Comment by tcgumus** [comment]
can you try lovercase username? i have changes some the usernames that duplicates. You can check it on database.

**Comment by corner82** [comment]
my username is already lowercase, I think this involves something more
complicated we missed out before, I will look at it...

On Mon, Aug 3, 2015 at 10:28 PM, Tuna Çağlar Gümüş <notifications@github.com

**Comment by tcgumus** [comment]
ok. please let me know. what was the username? maybe i can also check latest changes

**Comment by corner82** [comment]
username 'zeynel', password '1q2w3e4r' as always :)

On Mon, Aug 3, 2015 at 10:32 PM, Tuna Çağlar Gümüş <notifications@github.com

**Comment by tcgumus** [comment]
i checked the database but there is nothing wrong about it. i will check the code and inform you.

**Comment by tcgumus** [comment]
hello,
i have fixed this. The problem caused by a duplicated username for "zeynel". They were 2 account with the same name and you couldn't access it now since we have added controls. Now there are 4 account like zeynel, zeynel2, zeynel3 and zeynel4.
best
tuna
