### ISSUE TITLE
Register page error on my development repo

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#376]
'http://88.249.18.205:8090/ecoman_zeynel/register' page on my development repo page displays error as seen below

![error_page](https://cloud.githubusercontent.com/assets/5053878/9045926/e6e58ce2-3a2f-11e5-9558-4ba42dfdc1ff.png)

although my github repo is sync ; I should not figure out the errors reason, should be resolved...

**Comment by tcgumus** [comment]
REcaptcha class has been inserted to the system folder. Maybe .gitignore caused a problem on your local files. I will try to come to ostim tomorrow so we can check and load necessary system files.

**Comment by corner82** [comment]
maybe but realy weird problem, I'm wondering what caused this....

On Mon, Aug 3, 2015 at 10:42 PM, Tuna Çağlar Gümüş <notifications@github.com
