### ISSUE TITLE
Edit Flow data: show name of flow and allow changes to ALL fields

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#377]
- Flow name not shown, how am I sure i'm editing the correct flow?
- not possible to edit Flow name, family, Input/output. what if you made a typo in the flowname???

![image](https://cloud.githubusercontent.com/assets/11196956/9226211/fdb6e706-410d-11e5-8084-c763227f29fc.png)

![image](https://cloud.githubusercontent.com/assets/11196956/9226291/4fb783bc-410e-11e5-8d89-57b9d2e89e74.png)

**Comment by tcgumus** [comment]
You can't edit flow name because if you change it i won't be the same flow so you will also have to change every data related to it. So if you make a typo mistake you can easily copy values to "new flow" form and create a new flow then delete the old one. 

I have added flow information in edit flow page. I will also add information in other edit pages.

**Comment by catherine-moser** [comment]
i understand the problem with the flow NAME. but what about FAMILY and INPUT / OUTPUT?
how can i copy easily? i'm not aware of a copy function. i always have to type all the info in again.
I like the new "add flow" feature.
not sure what flow character means. there are no meaningful options for input flows.

**Comment by tcgumus** [comment]
There is no copt function. What i mean was that you can copy and paste with keyboard directly. Characters wanted from Ostim and i think there will be more options when we make a new meeting.

**Comment by catherine-moser** [comment]
i understand the problem with the flow NAME. but what about FAMILY and INPUT / OUTPUT?

**Comment by tcgumus** [comment]
The same thing will happen. In the allocations you are selecting flow type and making a allocation based on that. But i think you should be able to change flow family since we are not using it right now. Right?

**Comment by catherine-moser** [comment]
I don't care so much about the flow family. i care more about input/output. it happened to me, that I chose the input instead of output (a mistake happens quickly if you are entering a lot of flows). then it was very time consuming to enter the whole flow again.

**Comment by tcgumus** [comment]
Sorry, i can't do much about it right now.

**Comment by catherine-moser** [comment]
please at least show the user what flow he is editing! 
![image](https://cloud.githubusercontent.com/assets/11196956/9440683/4a2ebfa2-4a71-11e5-951c-5b9e5d437b70.png)

**Comment by tcgumus** [comment]
i have already done it

**Comment by catherine-moser** [comment]
yes now i can see it as well
![image](https://cloud.githubusercontent.com/assets/11196956/9440886/f78e90ae-4a72-11e5-9a2a-e787b9033327.png)
