### ISSUE TITLE
IMPORTANT BUG: EP values are cut off --> low numbers are not saved

### ISSUE THREAD

**Issue by catherine-moser** [Leadera/ecoman_repo#378]
I entered a low environmental impact
![image](https://cloud.githubusercontent.com/assets/11196956/9226610/bf116b50-410f-11e5-9b1f-33010ec03501.png)
saved, checked, saw it was zero
![image](https://cloud.githubusercontent.com/assets/11196956/9226637/d74a89fe-410f-11e5-9b8c-c3775dd76865.png)
clicked "edit" and saw my entry was lost!!!!!
![image](https://cloud.githubusercontent.com/assets/11196956/9226674/f969281a-410f-11e5-85d8-31766399d4cc.png)

This is very annoying, since the calculatin of Envirnonmental impacts can be very time consuming!

**Comment by catherine-moser** [comment]
Tuna, can you recover small EP values that were rounded to 0.00? Company name is "stag".
![image](https://cloud.githubusercontent.com/assets/11196956/9226860/e56fb224-4110-11e5-8572-70f52b34f65d.png)
![image](https://cloud.githubusercontent.com/assets/11196956/9226882/ffaecf3a-4110-11e5-8942-bd08a89b2b5c.png)

**Comment by tcgumus** [comment]
I wasn't a bug. We have limited EP values with 13 characters and 2 precision point for to save some load on database in the future. I have changed the EP values data type right now. Can you please try again?

**Comment by catherine-moser** [comment]
no change visible for me:
![image](https://cloud.githubusercontent.com/assets/11196956/9439822/ae60c54e-4a6a-11e5-8942-1cbc39999f08.png)

**Comment by tcgumus** [comment]
PLease try to edit them and enter the long data

**Comment by catherine-moser** [comment]
ok I tried:
- small number: ok, but can you show only "significant" numbers --> not the two zeros that don't have a meaning?
- big number: I think it would make sense to show this also as scientific.
- how common is this scientific notation in Turkey? do the people in OSTIM know it? I have discovered that in Switzerland it is not as common knowledge as I thought.
![image](https://cloud.githubusercontent.com/assets/11196956/9440224/acd6e796-4a6d-11e5-8bbf-0c94cd4020ec.png)

**Comment by catherine-moser** [comment]
could you recover my values (see post from 12 days ago (12 of august))?

**Comment by tcgumus** [comment]
I can't right now sorry. The notation is not common in turkey also it will be a problem to insert a float data to database as string. We won't be able to make calculations. Same question asked by Milda but we can't do it right now sorry.
