### ISSUE TITLE
Company info will be displayed on map with a toolbar button action depending on selected feature on map

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#388]
Company info will be displayed on map with a toolbar button action depending on selected feature on map

**Comment by corner82** [comment]
feature implemented, you can check it out...

**Comment by gmassard** [comment]
HI,

I can see the information on companies when I click on the ? button and then on a company logo. Good! But the information are display as a row, witch is difficult to navigate. Can we improve the design?
Have the information by display on a window where all information are visible with less scrolling to much.

**Comment by corner82** [comment]
Data has to be displayed in datagrid as usual, but I changed width and height of the pop up window, I think data can be tracked easier now, All we can do is to change width and height...
