### ISSUE TITLE
allocation percentage should be calculated by system

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#438]
On allocation issus, user inputs allovation values by himself,
This leads us big problems and user misinformation on database,
As we are tjkaing amounts already, system can easily calculate the percenatges and only shown to the user in disabled text areas as infos, this should be fixed immediately, thank you

**Comment by catherine-moser** [comment]
this is already adressed in issue #214, therfore I will close this issue.
Best, Catherine
