### ISSUE TITLE
Selection of company at step 2 of IS automated 

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#470]
IS automated detection page, step 2: 
- how to deselect companies when all are selected?
- is it possible that all line of same company get selected when clicking on one line only of that company? 
(if line is selected as in printscreen 1, all line of same company automatically are selected as in printscreen 2)

printscreen 1
![screen shot 2015-09-09 at 09 37 57](https://cloud.githubusercontent.com/assets/10558805/9755957/9f50faba-56d6-11e5-87a5-2f509f7cde15.png)

printscreen 2
![screen shot 2015-09-09 at 09 38 11](https://cloud.githubusercontent.com/assets/10558805/9755961/a36b48bc-56d6-11e5-89c3-c634a3791d08.png)

**Comment by corner82** [comment]
1- deselect all companies button has been added,
2- You do not to select same company multiple times, if you select a company once, system includes that company into the result automatically, so do not need to select all rows belonging to one company,(the datagrid has paging feature , if you even wanted you caanot beacause of paging ),
closing issue....

**Comment by gmassard** [comment]
Thank you for the new button and the explanation. Emily, we will include this in the user manual to make sure that users understand it!
