### ISSUE TITLE
IS automated page, step 3: display the symbiosis in logic  direction of flow

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#471]
IS automated detection page, step 3: the symbiosis should be displayed with input on the left and output on the right (logic direction of flow). Currently it displays in the reverse order sometime (see printscreen). 
![screen shot 2015-09-09 at 09 41 58](https://cloud.githubusercontent.com/assets/10558805/9756049/4368e61c-56d7-11e5-8d8c-3eef792b60bb.png)

**Comment by corner82** [comment]
This depends on 'IS scenario type' dropdown selection,
if you choose 'all IS candidates' input -output flows shown mixed as shown below,
![471_1](https://cloud.githubusercontent.com/assets/5053878/10247651/272d6f8c-6923-11e5-8201-e15e7324084d.png)

if you choose 'input mutualisation' input -input flows shown as below,
![471_2](https://cloud.githubusercontent.com/assets/5053878/10247693/75c0952a-6923-11e5-8864-09557f3fd943.png)


if you choose 'output mutualisation' output -output  flows shown as below,
![471_3](https://cloud.githubusercontent.com/assets/5053878/10247726/a6bdb8a6-6923-11e5-94f0-48c9939aebec.png)

if you choose 'input & output mutualisation' input -output flows shown  as below,
![471_4](https://cloud.githubusercontent.com/assets/5053878/10247788/0dd7ab00-6924-11e5-926a-0c5d8f980dcb.png)

closing this issue....
