### ISSUE TITLE
map of project does not appear

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#472]
Page of interest: http://88.249.18.205:8090/ecoman/project/45

on project page of Geneva_fti_case1: map of project does not appear (see printscreen)
![screen shot 2015-09-09 at 09 45 35](https://cloud.githubusercontent.com/assets/10558805/9756086/a52b61b8-56d7-11e5-9be0-400d7bee0478.png)

**Comment by tcgumus** [comment]
you need to wait a little bit

**Comment by emilyvuylsteke** [comment]
Even when I wait for 5 min with a strong internet connexion, the map still does not appear.

**Comment by corner82** [comment]
fixed, you may test page....

**Comment by gmassard** [comment]
Ok, the map works now!
Thank you
