### ISSUE TITLE
"input & output Mutualisation" IS not detected

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#473]
IS automated page, geneva_fti_test1: why is the IS between ABB and probéton not detected when we choose “input & output Mutualisation” as IS scenario Type? (It is detected when we choose "all IS candidates”) 
http://88.249.18.205:8090/ecoman/isScopingAutoPrjBaseMDF#add

**Comment by emilyvuylsteke** [comment]
also, could we modify the name of the IS scenario Type : replace “input & output Mutualisation” by “input & output exchange”.

**Comment by corner82** [comment]
this issue is related #508 , response waiting for both issues....

**Comment by corner82** [comment]
related issue closed, so this one is being closed too
