### ISSUE TITLE
Automated IS: Symbiosis not detected 

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#508]
Opened project: Geneva_fti_case1
Automated IS

I have two company in this project who could exchange organic waste (biogaz mandement and Ferme des grands bois). Nevertheless, the symbiosis is not detected (see printscreen). 

Is there a reason? I selected all flows, and all IS candidates. 

page of interest: http://88.249.18.205:8090/ecoman/isScopingAutoPrjBaseMDF#add

Related to issue 473

**Comment by emilyvuylsteke** [comment]
I had the same issue with the following symbiosis that should've been identified in the geneva-fti_case1 project:
LRG and "le porc de A à Z" who should be able to exchange "lactoserum"
LRG and Firmenich who should be able to exchange phosphoric acid

Is there something wrong with the way the flows are documented that prevents ecoman to detect de symbiosis? 

thanks in advance!

**Comment by corner82** [comment]
''I have two company in this project who could exchange organic waste (biogaz mandement and Ferme des grands bois). Nevertheless, the symbiosis is not detected (see printscreen)."

I tried to implement the same scenario, the page 'http://88.249.18.205:8090/ecoman/isScopingAutoPrjBaseMDF#add' same as you referred,
I'm sharing the screen shots, 

I selected all flows,
![508_1](https://cloud.githubusercontent.com/assets/5053878/10246809/0dd824ba-691d-11e5-8b4b-22f6a3619dc5.png)

I choose biogaz mandement and Ferme des grands bois,
![508_2](https://cloud.githubusercontent.com/assets/5053878/10246835/437640e8-691d-11e5-9f70-72f1a06e31f9.png)

When I clicked 'calculate IS' button, here is the result,
![508_3](https://cloud.githubusercontent.com/assets/5053878/10246869/8e3f7e82-691d-11e5-9b70-e753aa7b946a.png)

I think my test works well, but if you do something different please inform us, thanks...

**Comment by gmassard** [comment]
Hi Zeynel,

I just did the same test again, using the organic waste flow. Here is what I get..
Emily told me that some time it works, some time not. How can we make it 100% sure that the detection works?

![geneva_test_8](https://cloud.githubusercontent.com/assets/9587966/10782538/69920bca-7d51-11e5-93c4-2228cead5106.png)

**Comment by gmassard** [comment]
Hi Zeynel, as you asked for, here is a screen shoot of the data I selected for automatic IS detection and got no results:
![geneva_test_9](https://cloud.githubusercontent.com/assets/9587966/10783714/06e590ec-7d5a-11e5-9ef4-cccafa3d7c7a.png)

**Comment by corner82** [comment]
in which project (name) are you testing , I will open exact the same
project to look at in detail....

**Comment by gmassard** [comment]
The project is called: geneva_fti_case1

**Comment by corner82** [comment]
Here is my results,
Opened project  'geneva_fti_case1'',
I selected all flows,
selected 'biogaz mandement' and 'ferme des grand bois', and here my results on may screen,

![issue508](https://cloud.githubusercontent.com/assets/5053878/10784619/dfce2740-7d67-11e5-8699-d64cc39fbfa9.png)

**Comment by gmassard** [comment]
Hi Zeynel,
Ok, now it seems to work again! I will close the issue.
Should we talk on hangout?
