### ISSUE TITLE
Manual IS, terminology and data display

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#509]
Here below are some suggestions to make the process more understandable:

in table 1: 
- Change title of this table as "step 1: select a company for witch flow matching is required”
- Replace “begin manual IS process” by “get flows details for this company"

in table 2: 
- replace “get specific flow” by “create flow matching”

in table 4:
- add “step 4” in title
- In the line of the potential, the name of the 2 flows should display. It should displays like this: company/quantity/flow/company/quantity/flow/...

Thanks in advance!

**Comment by corner82** [comment]
check the modifications please...

**Comment by gmassard** [comment]
Modification are okay. I'm closing the issue!
thank you
