### ISSUE TITLE
Flow and process search implementation on map

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#512]
Flow and process search implementation on map due to 'GIS-17' use case scenario  on 'ECOMAN_use_cases_v1_xx_.docx' document

**Comment by corner82** [comment]
map api has been extended, issue closed....

**Comment by gmassard** [comment]
I do not find the search field? How to I make a request on a specific flow or process?

**Comment by gmassard** [comment]
Ok, now I found it. As we discuss, it would be nice to display more attributes on the search result. Also to export all attributes related to a flow.
Finally, the excel export was not working this morning

**Comment by gmassard** [comment]
The search functionality is now working. Great job.
To have it fully working and refine it, here are some improvements:
1. The search is displayed in a pop-up window, so are the search results. It would be more convenient if the search page will display on the left side or below the map. In particular, the search result can be displayed below the map. It is more convenient for users.
2. The search results need to display all attributes (columns) from a flow or a process. Please add all column to the table
3. It would be nice to have an search for company and equipments as well.

**Comment by corner82** [comment]
new issues related 2. and 3. topics are respectively #519, #520 ,
For the first topic, the search functionality is being described fully on 'IS-GIS use case document', all new code has been relied and extended due to this document, so for this version 1. topic cannot be implemented, new refinementes can be tracked from #519 and #520, issue closed
