### ISSUE TITLE
Modification for Manual Is scenarios

### ISSUE THREAD

**Issue by corner82** [Leadera/ecoman_repo#516]
For manual IS scenarios some modifications are required,
First on database level, then on service layer new service will be tested,
Secondly for 'manual IS' and 'IS list scenarios' user interface modifications will be made, related issue #510

**Comment by corner82** [comment]
Database , service layer and user interface modifications has been done, please test , since the database has been changed, some IS scenario data has been inserted in project 'GENEVA_FTI_CASE1' for consistency, you may alter or delete old scenarios, thank you...

**Comment by gmassard** [comment]
Hi Zeynel,

I check the IS scenario page. Now the name of the flow for each company appears. The test is successfull. Thank you
