### ISSUE TITLE
Can not connect to the IS potential identification pages for my projects

### ISSUE THREAD

**Issue by gmassard** [Leadera/ecoman_repo#569]
When I try to connect to manuel detection, automated detection or the scenario pages, I got the following message:
404 Page Not Found :(

Zeynel, can you please check?

Thank you, Guillaume

**Comment by corner82** [comment]
@gmassard
I can enter pages
here are my link which is working,
http://88.249.18.205:8090/ecoman/isScopingPrjBaseMDF
http://88.249.18.205:8090/ecoman/isScopingAutoPrjBaseMDF
http://88.249.18.205:8090/ecoman/isscenarios
http://88.249.18.205:8090/ecoman/isscenariosCns

P.S. did you open an project ?

**Comment by gmassard** [comment]
Hi Zeynel,

I test again today and it works.
Yes, yesterday I had a project open when I got the error message.
But everything seems to be alright today.
I'm closing the issue, thank you!
Best

Guillaume
