### ISSUE TITLE
There is no buttom on the company list page to create a new company

### ISSUE THREAD

**Issue by Ecoxl** [Leadera/ecoman_repo#63]
Dear Tuna
This is my first trail :-)
We can not create a new Company on the page  http://88.249.18.205:8090/ecoman/company. 
Milda told be there was a button on thies page.
Cheers Dirk

**Comment by tcgumus** [comment]
Hello,
We have decided 1 company limit for every user is not necessary. So, i have enabled it again. Now you should be able to add as many company as you want. Please test and respond :)

**Comment by corner82** [comment]
Please test this issue, label has been changed to 'waiting for test', if the requirement is fullfilled , tester may close this issue

**Comment by MildaMa** [comment]
Hi,
Yes, I can open new Company now, but it seems that it still doesn`t work properly. I can`t edit my new company. There is no "Dataset Management" for the Company that I just created (Company G) and it is not marked as Editable in my List of Companies. Please see attached. 
Best,
Milda
![file-page1](https://cloud.githubusercontent.com/assets/9460158/6128419/f0f824ca-b135-11e4-8b20-a1905d93aed1.jpg)

**Comment by tcgumus** [comment]
Hello,

can you please try again?

thank you

Saygılarımla / Best Regards,
Tuna Çağlar GÜMÜŞ

2015-02-10 16:08 GMT+02:00 MildaMa <notifications@github.com>:

**Comment by tcgumus** [comment]
Please create a new company from zero.

**Comment by MildaMa** [comment]
Now it works!
Thanks :)
