### ISSUE TITLE
If the user does not provide the flow attribute there should be empty not "0"  in the table

### ISSUE THREAD

**Issue by MildaMa** [Leadera/ecoman_repo#67]
e.g. if I do not provide the pH value there is a "0" in the table of flows. It should be empty. The same for concentration, pressure, state

**Comment by tcgumus** [comment]
I have solved both of the problems. You can now enter empty values and it wont show as 0. it also doesnt insert anything if it is null. I have also changes state description. Now you can see states as you choose. :+1:
