### ISSUE TITLE
Units for "cencentration" and  "pressure" of flows

### ISSUE THREAD

**Issue by MildaMa** [Leadera/ecoman_repo#69]

**Comment by tcgumus** [comment]
What kind of units are we looking for?

**Comment by gmassard** [comment]
About IS, the unit use for Concentration are mostly % or kg/m3 for exemple.
The unit for pressure are: Pascal (Pa), bar (Bar) or Standard atmosphere (atm)

**Comment by tcgumus** [comment]
New unit fields have been added. 
![image](https://cloud.githubusercontent.com/assets/2714346/6867570/22a08ee4-d48c-11e4-9a89-8227458b9e4a.png)

**Comment by catherine-moser** [comment]
thanks!
