### ISSUE TITLE
company contact person

### ISSUE THREAD

**Issue by etolan11** [Leadera/ecoman_repo#7]
proje oluştururken otomatik olarak company 'nin contact person ' ı proje ile ilişkilendirilmiyor. tablo güncellenince yapılacak

**Comment by catherine-moser** [comment]
Not sure what the discussion meant so far :-) , but I think it would be a good idea to also add a contact person for a company (as for a project).

**Comment by tcgumus** [comment]
He was talking about the contact persons of project that taken from companies. Thats why he summarize it as "company contact person". Companies has already have contact person. The user that created the company is its contact person.

**Comment by catherine-moser** [comment]
ok but this person is not listed on the companies page like on the project page. Anyway i find the design of the project page easier to read, maybe you could make the company page look alike?
![image](https://cloud.githubusercontent.com/assets/11196956/8126790/f60661d6-10f1-11e5-9e0c-91aee5905d64.png)
![image](https://cloud.githubusercontent.com/assets/11196956/8126800/02428bb4-10f2-11e5-8a9d-25cd989cda72.png)

**Comment by tcgumus** [comment]
New designs has been added.

**Comment by catherine-moser** [comment]
thanks for the redesign, i think it looks good!
but the conact person is still not listed, only all associated users. so whom should I contact if I want to make a project with this company? can you add "contact person" like in project? 
![image](https://cloud.githubusercontent.com/assets/11196956/8522868/1c69a92e-23f2-11e5-8da4-0ca064e0f936.png)

**Comment by catherine-moser** [comment]
why did you close this? my question form the 6 of July is still open.
