### ISSUE TITLE
There should be a possibility to add a new "flow family"

### ISSUE THREAD

**Issue by MildaMa** [Leadera/ecoman_repo#71]

**Comment by tcgumus** [comment]
We are thinking about this s a feature of admin module. I think we can start admin module after 1.0 version.

If there are flow families that we should add, just send us as a email and we can add manually from database.

**Comment by corner82** [comment]
Admin page for this issue has been prepared, link http://88.249.18.205:8090/ecoman/admin/newFlow, first user must log onto system, for test purposes any user can see admin pages
