### ISSUE TITLE
"Process family" should not be required when the new process is added

### ISSUE THREAD

**Issue by MildaMa** [Leadera/ecoman_repo#72]
Page of interest: http://88.249.18.205:8090/ecoman/new_process/63

**Comment by tcgumus** [comment]
Process should be associated with a process family. if you open this issue since you couldnt create a new process family, we will provide an admin functionality to be able to add new process familes after 1.0 so this problem can be solved.

**Comment by MildaMa** [comment]
Hi,
I still think it should not be required. Most probably the user will not be able to assign those types of "Process families" (like "main material intensive process" or "main energy intensive process") at the Dataset Management phase. In fact I don`t really see the need for it since in my opinion the tool should help the user to identify the most energy intensive or the most material intensive process.
If there is no technical possibility to change it, there should be at least "other" Option for "Process Family" selection.
Regards
Milda

**Comment by corner82** [comment]
Admin page for this issue has been prepared, link http://88.249.18.205:8090/ecoman/admin/newProcess, first user must log onto system, for test purposes any user can see admin pages
