### ISSUE TITLE
"create company" button

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#95]
Page of interest: http://88.249.18.205:8090/ecoman/company
Please add the “create company” button for every consultant user. When I am logged in as Emily_vuylsteke, I do not have the button “create a company” on the company page, but I am able to create one by accessing through the following link: 
http://88.249.18.205:8090/ecoman/newcompany.

**Comment by corner82** [comment]
Mr.Tuna has been coded related code blocks, so I assign him this issue, he later can mark milestone...

**Comment by emilyvuylsteke** [comment]
Thanks for this
