### ISSUE TITLE
Company creation: address entry box 

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#98]
Page of interest: http://88.249.18.205:8090/ecoman/newcompany

Can you add an address entry box for the localization of the company?

**Comment by corner82** [comment]
Mr.Tuna has been coded related code blocks, so I assign him this issue, he later can mark milestone...

**Comment by gmassard** [comment]
This issue is related to GIS functionalities. Zeynel, can't you deal with is directly?

**Comment by tcgumus** [comment]
Hello,
There is one field for address already. Are you referring to the country selection field or something different? Or you want more than 1 field for addres?
Thank you.

![image](https://cloud.githubusercontent.com/assets/2714346/6108869/2ff4caaa-b07f-11e4-9117-deb01ffc66ed.png)

**Comment by gmassard** [comment]
This issue is related to GIS functionalities. When creating a company, we can locate it on a map. But when the map open, it is centered on Ostim and the user has to find the company location by navigating on the map and using zoom in zoom out buttons.
Can we link the map opening to the address (or al least country) field on the company creation page, so that when the map opens, it is directly centered on the company address (or country)??

I think this issue is for Zeynel, more than for Tuna...

Thank you! Guillaume

**Comment by corner82** [comment]
For this feature we have to implement 'country' data for company and project. After this refinement we can get the country info from project or company entities and map can be centered on related geographic position. I think we should put that 'country' info for project and companies and of course we sould think about if we have multinational projects....

**Comment by gmassard** [comment]
Ok, map can be centered on the main country of a project.
New when we create a project, the map is centered on central Europe, and then, once define, on the central location of a project as defined by the consultant.
this seems to work fine.

Next step: when a consultant is creating a company profile, is has to zoom on the map to find the company only by recognizing it visually on the map. Would it be possible to add a search field just like in google map? You type an address and the map center and zoom directly on this address?

**Comment by gmassard** [comment]
When I refer to the address field, I think it should be display after cliking on the "select on map" button.
Other option, the map automatically recognize the information written in the "Address" field on the "Create company page".
Zeynel, what can we do about it?

**Comment by corner82** [comment]
We can use google plugin directly for this purpose  I guess, cause that
feature is not feed and free as I remember....I will look at it in details..

**Comment by emilyvuylsteke** [comment]
This issue is related to the issue number 259. I will close this issue and we can deal with these aspects in issue number 259.
