### ISSUE TITLE
Allow empty fields when entering a new flow

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#99]
Page of interest:  http://88.249.18.205:8090/ecoman/new_flow/65

Can you allow empty fields in the creation of a new flow (no data, eg for EP and cost)?

**Comment by corner82** [comment]
Mr.Tuna has been coded related code blocks, so I assign him this issue, he later can mark milestone...

**Comment by tcgumus** [comment]
i think it should be discussed since it can effect Cp scoping, kpi calculation and cba modules since we are using these data from dataset in them. I will mark as response waiting and we can all share our ideas in comments

**Comment by gmassard** [comment]
We should be able to not enter data on one field. Then the program should tel us when generation a KPI table or graph that no data has been entered.
If this is too complicated, it should then only be mandatory to enter data for some field, not for all of them. While testing, I so far do not understand what data is expected sometime. We will have the same problem with many users in the futur. so the program should allow empty field, but then warn users that no table can be generated.

**Comment by gmassard** [comment]
Hi the EP field is still mandatory and all data provided disappear when you click on create flow if the EP is not entered. Can we improve that to facilitate data introduction?

**Comment by catherine-moser** [comment]
Also if you enter a flow name that does not fulfill the requirements (e.g. with spaces) you get an error prompt and ALL the entered data disappears. Is it possible to store the data temporarily so that the user only needs to change the name of the flow?

**Comment by tcgumus** [comment]
You can now enter new flows with a space on it.

@catherine-moser yes but it should be another issue.

**Comment by catherine-moser** [comment]
flowname with space works. also data is stored in case of error (except flow name but I think we (Tuna and I) discussed the reason and agreed not to fix that).

**Comment by tcgumus** [comment]
Yep. Sorry but we can't really do it since there thousands of accents and most of them can cause words to lost their meaning also it is a really long development case that we can't handle right now.

**Comment by catherine-moser** [comment]
Just to clearify, how it works now:
if you add a flow, no EP value is necessary.
if you create an allocation EP value is mandatory. --> display in CP Scoping is always possible.

if the allocation page is redesigned as proposed in #214 a problem will occur if no EP value of the flow was entered. An alert should tell the user that CP Scoping is not possible if no EP values are entered and offer the possiblity to add EP value.
